// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use crate::api::minos::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1097111868;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__minos__MobileClient_current_state_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "MobileClient_current_state",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let mut api_that_guard = None;
                let decode_indices_ =
                    flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                        flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                            &api_that, 0, false,
                        ),
                    ]);
                for i in decode_indices_ {
                    match i {
                        0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                        _ => unreachable!(),
                    }
                }
                let api_that_guard = api_that_guard.unwrap();
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::minos::MobileClient::current_state(&*api_that_guard),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__minos__MobileClient_new_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "MobileClient_new",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_self_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::minos::MobileClient::new(api_self_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__minos__MobileClient_pair_with_json_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "MobileClient_pair_with_json",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>,
            >>::sse_decode(&mut deserializer);
            let api_qr_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::minos::MinosError>(
                    (move || async move {
                        let mut api_that_guard = None;
                        let decode_indices_ =
                            flutter_rust_bridge::for_generated::lockable_compute_decode_order(
                                vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                    &api_that, 0, false,
                                )],
                            );
                        for i in decode_indices_ {
                            match i {
                                0 => {
                                    api_that_guard =
                                        Some(api_that.lockable_decode_async_ref().await)
                                }
                                _ => unreachable!(),
                            }
                        }
                        let api_that_guard = api_that_guard.unwrap();
                        let output_ok = crate::api::minos::MobileClient::pair_with_json(
                            &*api_that_guard,
                            api_qr_json,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__minos__MobileClient_subscribe_state_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "MobileClient_subscribe_state",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <RustOpaqueMoi<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>,
            >>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::minos::ConnectionState,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, false,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref()),
                            _ => unreachable!(),
                        }
                    }
                    let api_that_guard = api_that_guard.unwrap();
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::minos::MobileClient::subscribe_state(
                            &*api_that_guard,
                            api_sink,
                        );
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__minos__init_logging_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_logging",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_log_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::minos::MinosError>((move || {
                    let output_ok = crate::api::minos::init_logging(api_log_dir)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__minos__kind_message_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "kind_message",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_kind = <crate::api::minos::ErrorKind>::sse_decode(&mut deserializer);
            let api_lang = <crate::api::minos::Lang>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::minos::kind_message(api_kind, api_lang))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: static_checks

#[allow(clippy::unnecessary_literal_unwrap)]
const _: fn() = || {
    match None::<crate::api::minos::ConnectionState>.unwrap() {
        crate::api::minos::ConnectionState::Disconnected => {}
        crate::api::minos::ConnectionState::Pairing => {}
        crate::api::minos::ConnectionState::Connected => {}
        crate::api::minos::ConnectionState::Reconnecting { attempt } => {
            let _: u32 = attempt;
        }
    }
    match None::<crate::api::minos::MinosError>.unwrap() {
        crate::api::minos::MinosError::BindFailed { addr, message } => {
            let _: String = addr;
            let _: String = message;
        }
        crate::api::minos::MinosError::ConnectFailed { url, message } => {
            let _: String = url;
            let _: String = message;
        }
        crate::api::minos::MinosError::Disconnected { reason } => {
            let _: String = reason;
        }
        crate::api::minos::MinosError::PairingTokenInvalid => {}
        crate::api::minos::MinosError::PairingStateMismatch { actual } => {
            let _: crate::api::minos::PairingState = actual;
        }
        crate::api::minos::MinosError::DeviceNotTrusted { device_id } => {
            let _: String = device_id;
        }
        crate::api::minos::MinosError::StoreIo { path, message } => {
            let _: String = path;
            let _: String = message;
        }
        crate::api::minos::MinosError::StoreCorrupt { path, message } => {
            let _: String = path;
            let _: String = message;
        }
        crate::api::minos::MinosError::CliProbeTimeout { bin, timeout_ms } => {
            let _: String = bin;
            let _: u64 = timeout_ms;
        }
        crate::api::minos::MinosError::CliProbeFailed { bin, message } => {
            let _: String = bin;
            let _: String = message;
        }
        crate::api::minos::MinosError::RpcCallFailed { method, message } => {
            let _: String = method;
            let _: String = message;
        }
        crate::api::minos::MinosError::Unauthorized { reason } => {
            let _: String = reason;
        }
        crate::api::minos::MinosError::ConnectionStateMismatch { expected, actual } => {
            let _: String = expected;
            let _: String = actual;
        }
        crate::api::minos::MinosError::EnvelopeVersionUnsupported { version } => {
            let _: u8 = version;
        }
        crate::api::minos::MinosError::PeerOffline { peer_device_id } => {
            let _: String = peer_device_id;
        }
        crate::api::minos::MinosError::RelayInternal { message } => {
            let _: String = message;
        }
        crate::api::minos::MinosError::CodexSpawnFailed { message } => {
            let _: String = message;
        }
        crate::api::minos::MinosError::CodexConnectFailed { url, message } => {
            let _: String = url;
            let _: String = message;
        }
        crate::api::minos::MinosError::CodexProtocolError { method, message } => {
            let _: String = method;
            let _: String = message;
        }
        crate::api::minos::MinosError::AgentAlreadyRunning => {}
        crate::api::minos::MinosError::AgentNotRunning => {}
        crate::api::minos::MinosError::AgentNotSupported { agent } => {
            let _: crate::api::minos::AgentName = agent;
        }
        crate::api::minos::MinosError::AgentSessionIdMismatch => {}
        crate::api::minos::MinosError::CfAccessMisconfigured { reason } => {
            let _: String = reason;
        }
        crate::api::minos::MinosError::IngestSeqConflict { thread_id, seq } => {
            let _: String = thread_id;
            let _: u64 = seq;
        }
        crate::api::minos::MinosError::ThreadNotFound { thread_id } => {
            let _: String = thread_id;
        }
        crate::api::minos::MinosError::TranslationNotImplemented { agent } => {
            let _: crate::api::minos::AgentName = agent;
        }
        crate::api::minos::MinosError::TranslationFailed { agent, message } => {
            let _: crate::api::minos::AgentName = agent;
            let _: String = message;
        }
    }
    {
        let PairResponse = None::<crate::api::minos::PairResponse>.unwrap();
        let _: bool = PairResponse.ok;
        let _: String = PairResponse.mac_name;
    }
};

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>
);

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for MobileClient {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::minos::ConnectionState, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::minos::AgentName {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::minos::AgentName::Codex,
            1 => crate::api::minos::AgentName::Claude,
            2 => crate::api::minos::AgentName::Gemini,
            _ => unreachable!("Invalid variant for AgentName: {}", inner),
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::minos::ConnectionState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::minos::ConnectionState::Disconnected;
            }
            1 => {
                return crate::api::minos::ConnectionState::Pairing;
            }
            2 => {
                return crate::api::minos::ConnectionState::Connected;
            }
            3 => {
                let mut var_attempt = <u32>::sse_decode(deserializer);
                return crate::api::minos::ConnectionState::Reconnecting {
                    attempt: var_attempt,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::minos::ErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::minos::ErrorKind::BindFailed,
            1 => crate::api::minos::ErrorKind::ConnectFailed,
            2 => crate::api::minos::ErrorKind::Disconnected,
            3 => crate::api::minos::ErrorKind::PairingTokenInvalid,
            4 => crate::api::minos::ErrorKind::PairingStateMismatch,
            5 => crate::api::minos::ErrorKind::DeviceNotTrusted,
            6 => crate::api::minos::ErrorKind::StoreIo,
            7 => crate::api::minos::ErrorKind::StoreCorrupt,
            8 => crate::api::minos::ErrorKind::CliProbeTimeout,
            9 => crate::api::minos::ErrorKind::CliProbeFailed,
            10 => crate::api::minos::ErrorKind::RpcCallFailed,
            11 => crate::api::minos::ErrorKind::Unauthorized,
            12 => crate::api::minos::ErrorKind::ConnectionStateMismatch,
            13 => crate::api::minos::ErrorKind::EnvelopeVersionUnsupported,
            14 => crate::api::minos::ErrorKind::PeerOffline,
            15 => crate::api::minos::ErrorKind::RelayInternal,
            16 => crate::api::minos::ErrorKind::CodexSpawnFailed,
            17 => crate::api::minos::ErrorKind::CodexConnectFailed,
            18 => crate::api::minos::ErrorKind::CodexProtocolError,
            19 => crate::api::minos::ErrorKind::AgentAlreadyRunning,
            20 => crate::api::minos::ErrorKind::AgentNotRunning,
            21 => crate::api::minos::ErrorKind::AgentNotSupported,
            22 => crate::api::minos::ErrorKind::AgentSessionIdMismatch,
            23 => crate::api::minos::ErrorKind::CfAccessMisconfigured,
            24 => crate::api::minos::ErrorKind::IngestSeqConflict,
            25 => crate::api::minos::ErrorKind::ThreadNotFound,
            26 => crate::api::minos::ErrorKind::TranslationNotImplemented,
            27 => crate::api::minos::ErrorKind::TranslationFailed,
            _ => unreachable!("Invalid variant for ErrorKind: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::minos::Lang {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::minos::Lang::Zh,
            1 => crate::api::minos::Lang::En,
            _ => unreachable!("Invalid variant for Lang: {}", inner),
        };
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::minos::MinosError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_addr = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::BindFailed {
                    addr: var_addr,
                    message: var_message,
                };
            }
            1 => {
                let mut var_url = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::ConnectFailed {
                    url: var_url,
                    message: var_message,
                };
            }
            2 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::Disconnected { reason: var_reason };
            }
            3 => {
                return crate::api::minos::MinosError::PairingTokenInvalid;
            }
            4 => {
                let mut var_actual = <crate::api::minos::PairingState>::sse_decode(deserializer);
                return crate::api::minos::MinosError::PairingStateMismatch { actual: var_actual };
            }
            5 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::DeviceNotTrusted {
                    device_id: var_deviceId,
                };
            }
            6 => {
                let mut var_path = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::StoreIo {
                    path: var_path,
                    message: var_message,
                };
            }
            7 => {
                let mut var_path = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::StoreCorrupt {
                    path: var_path,
                    message: var_message,
                };
            }
            8 => {
                let mut var_bin = <String>::sse_decode(deserializer);
                let mut var_timeoutMs = <u64>::sse_decode(deserializer);
                return crate::api::minos::MinosError::CliProbeTimeout {
                    bin: var_bin,
                    timeout_ms: var_timeoutMs,
                };
            }
            9 => {
                let mut var_bin = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::CliProbeFailed {
                    bin: var_bin,
                    message: var_message,
                };
            }
            10 => {
                let mut var_method = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::RpcCallFailed {
                    method: var_method,
                    message: var_message,
                };
            }
            11 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::Unauthorized { reason: var_reason };
            }
            12 => {
                let mut var_expected = <String>::sse_decode(deserializer);
                let mut var_actual = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::ConnectionStateMismatch {
                    expected: var_expected,
                    actual: var_actual,
                };
            }
            13 => {
                let mut var_version = <u8>::sse_decode(deserializer);
                return crate::api::minos::MinosError::EnvelopeVersionUnsupported {
                    version: var_version,
                };
            }
            14 => {
                let mut var_peerDeviceId = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::PeerOffline {
                    peer_device_id: var_peerDeviceId,
                };
            }
            15 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::RelayInternal {
                    message: var_message,
                };
            }
            16 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::CodexSpawnFailed {
                    message: var_message,
                };
            }
            17 => {
                let mut var_url = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::CodexConnectFailed {
                    url: var_url,
                    message: var_message,
                };
            }
            18 => {
                let mut var_method = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::CodexProtocolError {
                    method: var_method,
                    message: var_message,
                };
            }
            19 => {
                return crate::api::minos::MinosError::AgentAlreadyRunning;
            }
            20 => {
                return crate::api::minos::MinosError::AgentNotRunning;
            }
            21 => {
                let mut var_agent = <crate::api::minos::AgentName>::sse_decode(deserializer);
                return crate::api::minos::MinosError::AgentNotSupported { agent: var_agent };
            }
            22 => {
                return crate::api::minos::MinosError::AgentSessionIdMismatch;
            }
            23 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::CfAccessMisconfigured { reason: var_reason };
            }
            24 => {
                let mut var_threadId = <String>::sse_decode(deserializer);
                let mut var_seq = <u64>::sse_decode(deserializer);
                return crate::api::minos::MinosError::IngestSeqConflict {
                    thread_id: var_threadId,
                    seq: var_seq,
                };
            }
            25 => {
                let mut var_threadId = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::ThreadNotFound {
                    thread_id: var_threadId,
                };
            }
            26 => {
                let mut var_agent = <crate::api::minos::AgentName>::sse_decode(deserializer);
                return crate::api::minos::MinosError::TranslationNotImplemented {
                    agent: var_agent,
                };
            }
            27 => {
                let mut var_agent = <crate::api::minos::AgentName>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::minos::MinosError::TranslationFailed {
                    agent: var_agent,
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::minos::PairResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_macName = <String>::sse_decode(deserializer);
        return crate::api::minos::PairResponse {
            ok: var_ok,
            mac_name: var_macName,
        };
    }
}

impl SseDecode for crate::api::minos::PairingState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::minos::PairingState::Unpaired,
            1 => crate::api::minos::PairingState::AwaitingPeer,
            2 => crate::api::minos::PairingState::Paired,
            _ => unreachable!("Invalid variant for PairingState: {}", inner),
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__minos__MobileClient_pair_with_json_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__minos__MobileClient_subscribe_state_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__minos__init_logging_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__minos__MobileClient_current_state_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__minos__MobileClient_new_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__minos__kind_message_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<MobileClient> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<MobileClient> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<MobileClient>> for MobileClient {
    fn into_into_dart(self) -> FrbWrapper<MobileClient> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::AgentName> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::minos::AgentName::Codex => 0.into_dart(),
            crate::api::minos::AgentName::Claude => 1.into_dart(),
            crate::api::minos::AgentName::Gemini => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::AgentName>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::AgentName>>
    for crate::api::minos::AgentName
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::AgentName> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::ConnectionState> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::minos::ConnectionState::Disconnected => [0.into_dart()].into_dart(),
            crate::api::minos::ConnectionState::Pairing => [1.into_dart()].into_dart(),
            crate::api::minos::ConnectionState::Connected => [2.into_dart()].into_dart(),
            crate::api::minos::ConnectionState::Reconnecting { attempt } => {
                [3.into_dart(), attempt.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::ConnectionState>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::ConnectionState>>
    for crate::api::minos::ConnectionState
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::ConnectionState> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::ErrorKind> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::minos::ErrorKind::BindFailed => 0.into_dart(),
            crate::api::minos::ErrorKind::ConnectFailed => 1.into_dart(),
            crate::api::minos::ErrorKind::Disconnected => 2.into_dart(),
            crate::api::minos::ErrorKind::PairingTokenInvalid => 3.into_dart(),
            crate::api::minos::ErrorKind::PairingStateMismatch => 4.into_dart(),
            crate::api::minos::ErrorKind::DeviceNotTrusted => 5.into_dart(),
            crate::api::minos::ErrorKind::StoreIo => 6.into_dart(),
            crate::api::minos::ErrorKind::StoreCorrupt => 7.into_dart(),
            crate::api::minos::ErrorKind::CliProbeTimeout => 8.into_dart(),
            crate::api::minos::ErrorKind::CliProbeFailed => 9.into_dart(),
            crate::api::minos::ErrorKind::RpcCallFailed => 10.into_dart(),
            crate::api::minos::ErrorKind::Unauthorized => 11.into_dart(),
            crate::api::minos::ErrorKind::ConnectionStateMismatch => 12.into_dart(),
            crate::api::minos::ErrorKind::EnvelopeVersionUnsupported => 13.into_dart(),
            crate::api::minos::ErrorKind::PeerOffline => 14.into_dart(),
            crate::api::minos::ErrorKind::RelayInternal => 15.into_dart(),
            crate::api::minos::ErrorKind::CodexSpawnFailed => 16.into_dart(),
            crate::api::minos::ErrorKind::CodexConnectFailed => 17.into_dart(),
            crate::api::minos::ErrorKind::CodexProtocolError => 18.into_dart(),
            crate::api::minos::ErrorKind::AgentAlreadyRunning => 19.into_dart(),
            crate::api::minos::ErrorKind::AgentNotRunning => 20.into_dart(),
            crate::api::minos::ErrorKind::AgentNotSupported => 21.into_dart(),
            crate::api::minos::ErrorKind::AgentSessionIdMismatch => 22.into_dart(),
            crate::api::minos::ErrorKind::CfAccessMisconfigured => 23.into_dart(),
            crate::api::minos::ErrorKind::IngestSeqConflict => 24.into_dart(),
            crate::api::minos::ErrorKind::ThreadNotFound => 25.into_dart(),
            crate::api::minos::ErrorKind::TranslationNotImplemented => 26.into_dart(),
            crate::api::minos::ErrorKind::TranslationFailed => 27.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::ErrorKind>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::ErrorKind>>
    for crate::api::minos::ErrorKind
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::ErrorKind> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::Lang> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::minos::Lang::Zh => 0.into_dart(),
            crate::api::minos::Lang::En => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::Lang>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::Lang>>
    for crate::api::minos::Lang
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::Lang> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::MinosError> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::minos::MinosError::BindFailed { addr, message } => [
                0.into_dart(),
                addr.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::ConnectFailed { url, message } => [
                1.into_dart(),
                url.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::Disconnected { reason } => {
                [2.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::PairingTokenInvalid => [3.into_dart()].into_dart(),
            crate::api::minos::MinosError::PairingStateMismatch { actual } => {
                [4.into_dart(), actual.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::DeviceNotTrusted { device_id } => {
                [5.into_dart(), device_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::StoreIo { path, message } => [
                6.into_dart(),
                path.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::StoreCorrupt { path, message } => [
                7.into_dart(),
                path.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::CliProbeTimeout { bin, timeout_ms } => [
                8.into_dart(),
                bin.into_into_dart().into_dart(),
                timeout_ms.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::CliProbeFailed { bin, message } => [
                9.into_dart(),
                bin.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::RpcCallFailed { method, message } => [
                10.into_dart(),
                method.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::Unauthorized { reason } => {
                [11.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::ConnectionStateMismatch { expected, actual } => [
                12.into_dart(),
                expected.into_into_dart().into_dart(),
                actual.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::EnvelopeVersionUnsupported { version } => {
                [13.into_dart(), version.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::PeerOffline { peer_device_id } => {
                [14.into_dart(), peer_device_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::RelayInternal { message } => {
                [15.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::CodexSpawnFailed { message } => {
                [16.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::CodexConnectFailed { url, message } => [
                17.into_dart(),
                url.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::CodexProtocolError { method, message } => [
                18.into_dart(),
                method.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::AgentAlreadyRunning => [19.into_dart()].into_dart(),
            crate::api::minos::MinosError::AgentNotRunning => [20.into_dart()].into_dart(),
            crate::api::minos::MinosError::AgentNotSupported { agent } => {
                [21.into_dart(), agent.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::AgentSessionIdMismatch => [22.into_dart()].into_dart(),
            crate::api::minos::MinosError::CfAccessMisconfigured { reason } => {
                [23.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::IngestSeqConflict { thread_id, seq } => [
                24.into_dart(),
                thread_id.into_into_dart().into_dart(),
                seq.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::minos::MinosError::ThreadNotFound { thread_id } => {
                [25.into_dart(), thread_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::TranslationNotImplemented { agent } => {
                [26.into_dart(), agent.into_into_dart().into_dart()].into_dart()
            }
            crate::api::minos::MinosError::TranslationFailed { agent, message } => [
                27.into_dart(),
                agent.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::MinosError>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::MinosError>>
    for crate::api::minos::MinosError
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::MinosError> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::PairResponse> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.ok.into_into_dart().into_dart(),
            self.0.mac_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::PairResponse>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::PairResponse>>
    for crate::api::minos::PairResponse
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::PairResponse> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<crate::api::minos::PairingState> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            crate::api::minos::PairingState::Unpaired => 0.into_dart(),
            crate::api::minos::PairingState::AwaitingPeer => 1.into_dart(),
            crate::api::minos::PairingState::Paired => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<crate::api::minos::PairingState>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<crate::api::minos::PairingState>>
    for crate::api::minos::PairingState
{
    fn into_into_dart(self) -> FrbWrapper<crate::api::minos::PairingState> {
        self.into()
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for MobileClient {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::minos::ConnectionState, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::minos::AgentName {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::minos::AgentName::Codex => 0,
                crate::api::minos::AgentName::Claude => 1,
                crate::api::minos::AgentName::Gemini => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::minos::ConnectionState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::minos::ConnectionState::Disconnected => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::minos::ConnectionState::Pairing => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::minos::ConnectionState::Connected => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::minos::ConnectionState::Reconnecting { attempt } => {
                <i32>::sse_encode(3, serializer);
                <u32>::sse_encode(attempt, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::minos::ErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::minos::ErrorKind::BindFailed => 0,
                crate::api::minos::ErrorKind::ConnectFailed => 1,
                crate::api::minos::ErrorKind::Disconnected => 2,
                crate::api::minos::ErrorKind::PairingTokenInvalid => 3,
                crate::api::minos::ErrorKind::PairingStateMismatch => 4,
                crate::api::minos::ErrorKind::DeviceNotTrusted => 5,
                crate::api::minos::ErrorKind::StoreIo => 6,
                crate::api::minos::ErrorKind::StoreCorrupt => 7,
                crate::api::minos::ErrorKind::CliProbeTimeout => 8,
                crate::api::minos::ErrorKind::CliProbeFailed => 9,
                crate::api::minos::ErrorKind::RpcCallFailed => 10,
                crate::api::minos::ErrorKind::Unauthorized => 11,
                crate::api::minos::ErrorKind::ConnectionStateMismatch => 12,
                crate::api::minos::ErrorKind::EnvelopeVersionUnsupported => 13,
                crate::api::minos::ErrorKind::PeerOffline => 14,
                crate::api::minos::ErrorKind::RelayInternal => 15,
                crate::api::minos::ErrorKind::CodexSpawnFailed => 16,
                crate::api::minos::ErrorKind::CodexConnectFailed => 17,
                crate::api::minos::ErrorKind::CodexProtocolError => 18,
                crate::api::minos::ErrorKind::AgentAlreadyRunning => 19,
                crate::api::minos::ErrorKind::AgentNotRunning => 20,
                crate::api::minos::ErrorKind::AgentNotSupported => 21,
                crate::api::minos::ErrorKind::AgentSessionIdMismatch => 22,
                crate::api::minos::ErrorKind::CfAccessMisconfigured => 23,
                crate::api::minos::ErrorKind::IngestSeqConflict => 24,
                crate::api::minos::ErrorKind::ThreadNotFound => 25,
                crate::api::minos::ErrorKind::TranslationNotImplemented => 26,
                crate::api::minos::ErrorKind::TranslationFailed => 27,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::minos::Lang {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::minos::Lang::Zh => 0,
                crate::api::minos::Lang::En => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::minos::MinosError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::minos::MinosError::BindFailed { addr, message } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(addr, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::ConnectFailed { url, message } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(url, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::Disconnected { reason } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::minos::MinosError::PairingTokenInvalid => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::minos::MinosError::PairingStateMismatch { actual } => {
                <i32>::sse_encode(4, serializer);
                <crate::api::minos::PairingState>::sse_encode(actual, serializer);
            }
            crate::api::minos::MinosError::DeviceNotTrusted { device_id } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(device_id, serializer);
            }
            crate::api::minos::MinosError::StoreIo { path, message } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(path, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::StoreCorrupt { path, message } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(path, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::CliProbeTimeout { bin, timeout_ms } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(bin, serializer);
                <u64>::sse_encode(timeout_ms, serializer);
            }
            crate::api::minos::MinosError::CliProbeFailed { bin, message } => {
                <i32>::sse_encode(9, serializer);
                <String>::sse_encode(bin, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::RpcCallFailed { method, message } => {
                <i32>::sse_encode(10, serializer);
                <String>::sse_encode(method, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::Unauthorized { reason } => {
                <i32>::sse_encode(11, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::minos::MinosError::ConnectionStateMismatch { expected, actual } => {
                <i32>::sse_encode(12, serializer);
                <String>::sse_encode(expected, serializer);
                <String>::sse_encode(actual, serializer);
            }
            crate::api::minos::MinosError::EnvelopeVersionUnsupported { version } => {
                <i32>::sse_encode(13, serializer);
                <u8>::sse_encode(version, serializer);
            }
            crate::api::minos::MinosError::PeerOffline { peer_device_id } => {
                <i32>::sse_encode(14, serializer);
                <String>::sse_encode(peer_device_id, serializer);
            }
            crate::api::minos::MinosError::RelayInternal { message } => {
                <i32>::sse_encode(15, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::CodexSpawnFailed { message } => {
                <i32>::sse_encode(16, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::CodexConnectFailed { url, message } => {
                <i32>::sse_encode(17, serializer);
                <String>::sse_encode(url, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::CodexProtocolError { method, message } => {
                <i32>::sse_encode(18, serializer);
                <String>::sse_encode(method, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::minos::MinosError::AgentAlreadyRunning => {
                <i32>::sse_encode(19, serializer);
            }
            crate::api::minos::MinosError::AgentNotRunning => {
                <i32>::sse_encode(20, serializer);
            }
            crate::api::minos::MinosError::AgentNotSupported { agent } => {
                <i32>::sse_encode(21, serializer);
                <crate::api::minos::AgentName>::sse_encode(agent, serializer);
            }
            crate::api::minos::MinosError::AgentSessionIdMismatch => {
                <i32>::sse_encode(22, serializer);
            }
            crate::api::minos::MinosError::CfAccessMisconfigured { reason } => {
                <i32>::sse_encode(23, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::minos::MinosError::IngestSeqConflict { thread_id, seq } => {
                <i32>::sse_encode(24, serializer);
                <String>::sse_encode(thread_id, serializer);
                <u64>::sse_encode(seq, serializer);
            }
            crate::api::minos::MinosError::ThreadNotFound { thread_id } => {
                <i32>::sse_encode(25, serializer);
                <String>::sse_encode(thread_id, serializer);
            }
            crate::api::minos::MinosError::TranslationNotImplemented { agent } => {
                <i32>::sse_encode(26, serializer);
                <crate::api::minos::AgentName>::sse_encode(agent, serializer);
            }
            crate::api::minos::MinosError::TranslationFailed { agent, message } => {
                <i32>::sse_encode(27, serializer);
                <crate::api::minos::AgentName>::sse_encode(agent, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::minos::PairResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <String>::sse_encode(self.mac_name, serializer);
    }
}

impl SseEncode for crate::api::minos::PairingState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::minos::PairingState::Unpaired => 0,
                crate::api::minos::PairingState::AwaitingPeer => 1,
                crate::api::minos::PairingState::Paired => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::api::minos::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_minos_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_minos_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::api::minos::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
