//! `minos-codex-protocol` — typed Rust mirror of the codex app-server JSON-RPC
//! protocol.
//!
//! ## Layout
//!
//! - `client_request.rs` (hand-written) — `ClientRequest` and
//!   `ClientNotification` marker traits.
//! - `jsonrpc.rs` (hand-written) — JSON-RPC 2.0 envelope wire types.
//! - `generated/types.rs` (generated by typify) — every `*Params`,
//!   `*Response`, `*Notification`, plus all referenced helper types.
//! - `generated/methods.rs` (generated by `xtask gen-codex-protocol`'s
//!   post-processor) — `impl ClientRequest`/`impl ClientNotification` per
//!   method, plus `ServerRequest` / `ServerNotification` tagged enums.
//!
//! ## Regenerating
//!
//! ```sh
//! # Optional: refresh `schemas/` from a locally-installed codex CLI:
//! codex app-server generate-json-schema --out ./schemas
//!
//! # Mandatory: regenerate the Rust types from the current `schemas/`:
//! cargo xtask gen-codex-protocol
//! cargo test -p minos-codex-protocol
//! ```
//!
//! Both `schemas/` and `src/generated/` are committed to git. Schema upgrades
//! are a two-step PR: refresh `schemas/`, regenerate, commit both diffs.

#![forbid(unsafe_code)]

pub mod client_request;
pub mod generated;
pub mod jsonrpc;

pub use client_request::{ClientNotification, ClientRequest};
// Glob-export the generated `methods` module so synthesised marker structs
// (e.g. `InitializedNotification`, `AccountLogoutParams`) are available at
// the crate root alongside the four tagged-enum dispatch types. The `types`
// glob comes second so any name collision (none today) would prefer types.
pub use generated::methods::*;
pub use generated::types::*;
pub use jsonrpc::{JsonRpcError, JsonRpcErrorPayload, JsonRpcRequest, JsonRpcResponse};
