// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/minos.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MobileClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  MobileClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    dynamic raw,
  );

  @protected
  MobileClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    dynamic raw,
  );

  @protected
  MobileClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    dynamic raw,
  );

  @protected
  RustStreamSink<AuthStateFrame> dco_decode_StreamSink_auth_state_frame_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ConnectionState> dco_decode_StreamSink_connection_state_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogRecord> dco_decode_StreamSink_log_record_Sse(dynamic raw);

  @protected
  RustStreamSink<RequestTraceRecord>
  dco_decode_StreamSink_request_trace_record_Sse(dynamic raw);

  @protected
  RustStreamSink<UiEventFrame> dco_decode_StreamSink_ui_event_frame_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentDescriptor dco_decode_agent_descriptor(dynamic raw);

  @protected
  AgentName dco_decode_agent_name(dynamic raw);

  @protected
  AgentStatus dco_decode_agent_status(dynamic raw);

  @protected
  AuthStateFrame dco_decode_auth_state_frame(dynamic raw);

  @protected
  AuthSummary dco_decode_auth_summary(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AgentName dco_decode_box_autoadd_agent_name(dynamic raw);

  @protected
  AuthSummary dco_decode_box_autoadd_auth_summary(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ListThreadsParams dco_decode_box_autoadd_list_threads_params(dynamic raw);

  @protected
  MinosError dco_decode_box_autoadd_minos_error(dynamic raw);

  @protected
  PersistedPairingState dco_decode_box_autoadd_persisted_pairing_state(
    dynamic raw,
  );

  @protected
  ReadThreadParams dco_decode_box_autoadd_read_thread_params(dynamic raw);

  @protected
  ThreadEndReason dco_decode_box_autoadd_thread_end_reason(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UserSummary dco_decode_box_autoadd_user_summary(dynamic raw);

  @protected
  ChatMessageSummary dco_decode_chat_message_summary(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  ConversationKind dco_decode_conversation_kind(dynamic raw);

  @protected
  ConversationResponse dco_decode_conversation_response(dynamic raw);

  @protected
  ConversationSummary dco_decode_conversation_summary(dynamic raw);

  @protected
  ConversationsResponse dco_decode_conversations_response(dynamic raw);

  @protected
  ErrorKind dco_decode_error_kind(dynamic raw);

  @protected
  FriendRequestStatus dco_decode_friend_request_status(dynamic raw);

  @protected
  FriendRequestSummary dco_decode_friend_request_summary(dynamic raw);

  @protected
  FriendRequestsResponse dco_decode_friend_requests_response(dynamic raw);

  @protected
  FriendSummary dco_decode_friend_summary(dynamic raw);

  @protected
  FriendsResponse dco_decode_friends_response(dynamic raw);

  @protected
  HostSkillError dco_decode_host_skill_error(dynamic raw);

  @protected
  HostSkillSummary dco_decode_host_skill_summary(dynamic raw);

  @protected
  HostSkillsEntry dco_decode_host_skills_entry(dynamic raw);

  @protected
  HostSummaryDto dco_decode_host_summary_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Lang dco_decode_lang(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentDescriptor> dco_decode_list_agent_descriptor(dynamic raw);

  @protected
  List<ChatMessageSummary> dco_decode_list_chat_message_summary(dynamic raw);

  @protected
  ListChatMessagesResponse dco_decode_list_chat_messages_response(dynamic raw);

  @protected
  List<ConversationSummary> dco_decode_list_conversation_summary(dynamic raw);

  @protected
  List<FriendRequestSummary> dco_decode_list_friend_request_summary(
    dynamic raw,
  );

  @protected
  List<FriendSummary> dco_decode_list_friend_summary(dynamic raw);

  @protected
  List<HostSkillError> dco_decode_list_host_skill_error(dynamic raw);

  @protected
  List<HostSkillSummary> dco_decode_list_host_skill_summary(dynamic raw);

  @protected
  List<HostSkillsEntry> dco_decode_list_host_skills_entry(dynamic raw);

  @protected
  ListHostSkillsResponse dco_decode_list_host_skills_response(dynamic raw);

  @protected
  List<HostSummaryDto> dco_decode_list_host_summary_dto(dynamic raw);

  @protected
  List<LogRecord> dco_decode_list_log_record(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RequestTraceRecord> dco_decode_list_request_trace_record(dynamic raw);

  @protected
  List<ThreadSummary> dco_decode_list_thread_summary(dynamic raw);

  @protected
  ListThreadsParams dco_decode_list_threads_params(dynamic raw);

  @protected
  ListThreadsResponse dco_decode_list_threads_response(dynamic raw);

  @protected
  List<UiEventMessage> dco_decode_list_ui_event_message(dynamic raw);

  @protected
  List<UserSummary> dco_decode_list_user_summary(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  LogRecord dco_decode_log_record(dynamic raw);

  @protected
  MessageRole dco_decode_message_role(dynamic raw);

  @protected
  MinosError dco_decode_minos_error(dynamic raw);

  @protected
  MyProfileResponse dco_decode_my_profile_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AgentName? dco_decode_opt_box_autoadd_agent_name(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ThreadEndReason? dco_decode_opt_box_autoadd_thread_end_reason(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  UserSummary? dco_decode_opt_box_autoadd_user_summary(dynamic raw);

  @protected
  PairingState dco_decode_pairing_state(dynamic raw);

  @protected
  PersistedPairingState dco_decode_persisted_pairing_state(dynamic raw);

  @protected
  ReadThreadParams dco_decode_read_thread_params(dynamic raw);

  @protected
  ReadThreadResponse dco_decode_read_thread_response(dynamic raw);

  @protected
  RequestTraceRecord dco_decode_request_trace_record(dynamic raw);

  @protected
  RequestTraceStatus dco_decode_request_trace_status(dynamic raw);

  @protected
  RequestTraceTransport dco_decode_request_trace_transport(dynamic raw);

  @protected
  StartAgentResponse dco_decode_start_agent_response(dynamic raw);

  @protected
  ThreadEndReason dco_decode_thread_end_reason(dynamic raw);

  @protected
  ThreadSummary dco_decode_thread_summary(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiEventFrame dco_decode_ui_event_frame(dynamic raw);

  @protected
  UiEventMessage dco_decode_ui_event_message(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserSummary dco_decode_user_summary(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WriteHostSkillConfigResponse dco_decode_write_host_skill_config_response(
    dynamic raw,
  );

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  MobileClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    SseDeserializer deserializer,
  );

  @protected
  MobileClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    SseDeserializer deserializer,
  );

  @protected
  MobileClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AuthStateFrame> sse_decode_StreamSink_auth_state_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConnectionState> sse_decode_StreamSink_connection_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogRecord> sse_decode_StreamSink_log_record_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RequestTraceRecord>
  sse_decode_StreamSink_request_trace_record_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<UiEventFrame> sse_decode_StreamSink_ui_event_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentDescriptor sse_decode_agent_descriptor(SseDeserializer deserializer);

  @protected
  AgentName sse_decode_agent_name(SseDeserializer deserializer);

  @protected
  AgentStatus sse_decode_agent_status(SseDeserializer deserializer);

  @protected
  AuthStateFrame sse_decode_auth_state_frame(SseDeserializer deserializer);

  @protected
  AuthSummary sse_decode_auth_summary(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AgentName sse_decode_box_autoadd_agent_name(SseDeserializer deserializer);

  @protected
  AuthSummary sse_decode_box_autoadd_auth_summary(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ListThreadsParams sse_decode_box_autoadd_list_threads_params(
    SseDeserializer deserializer,
  );

  @protected
  MinosError sse_decode_box_autoadd_minos_error(SseDeserializer deserializer);

  @protected
  PersistedPairingState sse_decode_box_autoadd_persisted_pairing_state(
    SseDeserializer deserializer,
  );

  @protected
  ReadThreadParams sse_decode_box_autoadd_read_thread_params(
    SseDeserializer deserializer,
  );

  @protected
  ThreadEndReason sse_decode_box_autoadd_thread_end_reason(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserSummary sse_decode_box_autoadd_user_summary(SseDeserializer deserializer);

  @protected
  ChatMessageSummary sse_decode_chat_message_summary(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  ConversationKind sse_decode_conversation_kind(SseDeserializer deserializer);

  @protected
  ConversationResponse sse_decode_conversation_response(
    SseDeserializer deserializer,
  );

  @protected
  ConversationSummary sse_decode_conversation_summary(
    SseDeserializer deserializer,
  );

  @protected
  ConversationsResponse sse_decode_conversations_response(
    SseDeserializer deserializer,
  );

  @protected
  ErrorKind sse_decode_error_kind(SseDeserializer deserializer);

  @protected
  FriendRequestStatus sse_decode_friend_request_status(
    SseDeserializer deserializer,
  );

  @protected
  FriendRequestSummary sse_decode_friend_request_summary(
    SseDeserializer deserializer,
  );

  @protected
  FriendRequestsResponse sse_decode_friend_requests_response(
    SseDeserializer deserializer,
  );

  @protected
  FriendSummary sse_decode_friend_summary(SseDeserializer deserializer);

  @protected
  FriendsResponse sse_decode_friends_response(SseDeserializer deserializer);

  @protected
  HostSkillError sse_decode_host_skill_error(SseDeserializer deserializer);

  @protected
  HostSkillSummary sse_decode_host_skill_summary(SseDeserializer deserializer);

  @protected
  HostSkillsEntry sse_decode_host_skills_entry(SseDeserializer deserializer);

  @protected
  HostSummaryDto sse_decode_host_summary_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Lang sse_decode_lang(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentDescriptor> sse_decode_list_agent_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<ChatMessageSummary> sse_decode_list_chat_message_summary(
    SseDeserializer deserializer,
  );

  @protected
  ListChatMessagesResponse sse_decode_list_chat_messages_response(
    SseDeserializer deserializer,
  );

  @protected
  List<ConversationSummary> sse_decode_list_conversation_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<FriendRequestSummary> sse_decode_list_friend_request_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<FriendSummary> sse_decode_list_friend_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<HostSkillError> sse_decode_list_host_skill_error(
    SseDeserializer deserializer,
  );

  @protected
  List<HostSkillSummary> sse_decode_list_host_skill_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<HostSkillsEntry> sse_decode_list_host_skills_entry(
    SseDeserializer deserializer,
  );

  @protected
  ListHostSkillsResponse sse_decode_list_host_skills_response(
    SseDeserializer deserializer,
  );

  @protected
  List<HostSummaryDto> sse_decode_list_host_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LogRecord> sse_decode_list_log_record(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RequestTraceRecord> sse_decode_list_request_trace_record(
    SseDeserializer deserializer,
  );

  @protected
  List<ThreadSummary> sse_decode_list_thread_summary(
    SseDeserializer deserializer,
  );

  @protected
  ListThreadsParams sse_decode_list_threads_params(
    SseDeserializer deserializer,
  );

  @protected
  ListThreadsResponse sse_decode_list_threads_response(
    SseDeserializer deserializer,
  );

  @protected
  List<UiEventMessage> sse_decode_list_ui_event_message(
    SseDeserializer deserializer,
  );

  @protected
  List<UserSummary> sse_decode_list_user_summary(SseDeserializer deserializer);

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  LogRecord sse_decode_log_record(SseDeserializer deserializer);

  @protected
  MessageRole sse_decode_message_role(SseDeserializer deserializer);

  @protected
  MinosError sse_decode_minos_error(SseDeserializer deserializer);

  @protected
  MyProfileResponse sse_decode_my_profile_response(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AgentName? sse_decode_opt_box_autoadd_agent_name(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ThreadEndReason? sse_decode_opt_box_autoadd_thread_end_reason(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserSummary? sse_decode_opt_box_autoadd_user_summary(
    SseDeserializer deserializer,
  );

  @protected
  PairingState sse_decode_pairing_state(SseDeserializer deserializer);

  @protected
  PersistedPairingState sse_decode_persisted_pairing_state(
    SseDeserializer deserializer,
  );

  @protected
  ReadThreadParams sse_decode_read_thread_params(SseDeserializer deserializer);

  @protected
  ReadThreadResponse sse_decode_read_thread_response(
    SseDeserializer deserializer,
  );

  @protected
  RequestTraceRecord sse_decode_request_trace_record(
    SseDeserializer deserializer,
  );

  @protected
  RequestTraceStatus sse_decode_request_trace_status(
    SseDeserializer deserializer,
  );

  @protected
  RequestTraceTransport sse_decode_request_trace_transport(
    SseDeserializer deserializer,
  );

  @protected
  StartAgentResponse sse_decode_start_agent_response(
    SseDeserializer deserializer,
  );

  @protected
  ThreadEndReason sse_decode_thread_end_reason(SseDeserializer deserializer);

  @protected
  ThreadSummary sse_decode_thread_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiEventFrame sse_decode_ui_event_frame(SseDeserializer deserializer);

  @protected
  UiEventMessage sse_decode_ui_event_message(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserSummary sse_decode_user_summary(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WriteHostSkillConfigResponse sse_decode_write_host_skill_config_response(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    MobileClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    MobileClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    MobileClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_auth_state_frame_Sse(
    RustStreamSink<AuthStateFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_connection_state_Sse(
    RustStreamSink<ConnectionState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_record_Sse(
    RustStreamSink<LogRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_request_trace_record_Sse(
    RustStreamSink<RequestTraceRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_event_frame_Sse(
    RustStreamSink<UiEventFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_descriptor(
    AgentDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_name(AgentName self, SseSerializer serializer);

  @protected
  void sse_encode_agent_status(AgentStatus self, SseSerializer serializer);

  @protected
  void sse_encode_auth_state_frame(
    AuthStateFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_summary(AuthSummary self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_name(
    AgentName self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_auth_summary(
    AuthSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_threads_params(
    ListThreadsParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_minos_error(
    MinosError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_persisted_pairing_state(
    PersistedPairingState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_read_thread_params(
    ReadThreadParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_end_reason(
    ThreadEndReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_summary(
    UserSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message_summary(
    ChatMessageSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_kind(
    ConversationKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_response(
    ConversationResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_summary(
    ConversationSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversations_response(
    ConversationsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_error_kind(ErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_friend_request_status(
    FriendRequestStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_request_summary(
    FriendRequestSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_requests_response(
    FriendRequestsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_summary(FriendSummary self, SseSerializer serializer);

  @protected
  void sse_encode_friends_response(
    FriendsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_host_skill_error(
    HostSkillError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_host_skill_summary(
    HostSkillSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_host_skills_entry(
    HostSkillsEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_host_summary_dto(
    HostSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_lang(Lang self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_descriptor(
    List<AgentDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_message_summary(
    List<ChatMessageSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_messages_response(
    ListChatMessagesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_summary(
    List<ConversationSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_request_summary(
    List<FriendRequestSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_summary(
    List<FriendSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_host_skill_error(
    List<HostSkillError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_host_skill_summary(
    List<HostSkillSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_host_skills_entry(
    List<HostSkillsEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_host_skills_response(
    ListHostSkillsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_host_summary_dto(
    List<HostSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_log_record(
    List<LogRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_request_trace_record(
    List<RequestTraceRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_summary(
    List<ThreadSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_threads_params(
    ListThreadsParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_threads_response(
    ListThreadsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_event_message(
    List<UiEventMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_summary(
    List<UserSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_log_record(LogRecord self, SseSerializer serializer);

  @protected
  void sse_encode_message_role(MessageRole self, SseSerializer serializer);

  @protected
  void sse_encode_minos_error(MinosError self, SseSerializer serializer);

  @protected
  void sse_encode_my_profile_response(
    MyProfileResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_agent_name(
    AgentName? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thread_end_reason(
    ThreadEndReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_summary(
    UserSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_state(PairingState self, SseSerializer serializer);

  @protected
  void sse_encode_persisted_pairing_state(
    PersistedPairingState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_read_thread_params(
    ReadThreadParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_read_thread_response(
    ReadThreadResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_trace_record(
    RequestTraceRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_trace_status(
    RequestTraceStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_trace_transport(
    RequestTraceTransport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_start_agent_response(
    StartAgentResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thread_end_reason(
    ThreadEndReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thread_summary(ThreadSummary self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_event_frame(UiEventFrame self, SseSerializer serializer);

  @protected
  void sse_encode_ui_event_message(
    UiEventMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_summary(UserSummary self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_write_host_skill_config_response(
    WriteHostSkillConfigResponse self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    int ptr,
  );
}
