// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/minos.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1097111868;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'minos_ffi_frb',
        ioDirectory: '../../crates/minos-ffi-frb/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  ConnectionState crateApiMinosMobileClientCurrentState({
    required MobileClient that,
  });

  MobileClient crateApiMinosMobileClientNew({required String selfName});

  Future<PairResponse> crateApiMinosMobileClientPairWithJson({
    required MobileClient that,
    required String qrJson,
  });

  Stream<ConnectionState> crateApiMinosMobileClientSubscribeState({
    required MobileClient that,
  });

  Future<void> crateApiMinosInitLogging({required String logDir});

  String crateApiMinosKindMessage({
    required ErrorKind kind,
    required Lang lang,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MobileClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MobileClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MobileClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ConnectionState crateApiMinosMobileClientCurrentState({
    required MobileClient that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMinosMobileClientCurrentStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMinosMobileClientCurrentStateConstMeta =>
      const TaskConstMeta(
        debugName: "MobileClient_current_state",
        argNames: ["that"],
      );

  @override
  MobileClient crateApiMinosMobileClientNew({required String selfName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(selfName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMinosMobileClientNewConstMeta,
        argValues: [selfName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMinosMobileClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "MobileClient_new",
        argNames: ["selfName"],
      );

  @override
  Future<PairResponse> crateApiMinosMobileClientPairWithJson({
    required MobileClient that,
    required String qrJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
            that,
            serializer,
          );
          sse_encode_String(qrJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pair_response,
          decodeErrorData: sse_decode_minos_error,
        ),
        constMeta: kCrateApiMinosMobileClientPairWithJsonConstMeta,
        argValues: [that, qrJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMinosMobileClientPairWithJsonConstMeta =>
      const TaskConstMeta(
        debugName: "MobileClient_pair_with_json",
        argNames: ["that", "qrJson"],
      );

  @override
  Stream<ConnectionState> crateApiMinosMobileClientSubscribeState({
    required MobileClient that,
  }) {
    final sink = RustStreamSink<ConnectionState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_connection_state_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMinosMobileClientSubscribeStateConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMinosMobileClientSubscribeStateConstMeta =>
      const TaskConstMeta(
        debugName: "MobileClient_subscribe_state",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiMinosInitLogging({required String logDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(logDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_minos_error,
        ),
        constMeta: kCrateApiMinosInitLoggingConstMeta,
        argValues: [logDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMinosInitLoggingConstMeta =>
      const TaskConstMeta(debugName: "init_logging", argNames: ["logDir"]);

  @override
  String crateApiMinosKindMessage({
    required ErrorKind kind,
    required Lang lang,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_error_kind(kind, serializer);
          sse_encode_lang(lang, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMinosKindMessageConstMeta,
        argValues: [kind, lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMinosKindMessageConstMeta => const TaskConstMeta(
    debugName: "kind_message",
    argNames: ["kind", "lang"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MobileClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MobileClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MobileClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<ConnectionState> dco_decode_StreamSink_connection_state_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentName dco_decode_agent_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentName.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ConnectionState_Disconnected();
      case 1:
        return ConnectionState_Pairing();
      case 2:
        return ConnectionState_Connected();
      case 3:
        return ConnectionState_Reconnecting(attempt: dco_decode_u_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ErrorKind dco_decode_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ErrorKind.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Lang dco_decode_lang(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Lang.values[raw as int];
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MinosError dco_decode_minos_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MinosError_BindFailed(
          addr: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 1:
        return MinosError_ConnectFailed(
          url: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 2:
        return MinosError_Disconnected(reason: dco_decode_String(raw[1]));
      case 3:
        return MinosError_PairingTokenInvalid();
      case 4:
        return MinosError_PairingStateMismatch(
          actual: dco_decode_pairing_state(raw[1]),
        );
      case 5:
        return MinosError_DeviceNotTrusted(deviceId: dco_decode_String(raw[1]));
      case 6:
        return MinosError_StoreIo(
          path: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 7:
        return MinosError_StoreCorrupt(
          path: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 8:
        return MinosError_CliProbeTimeout(
          bin: dco_decode_String(raw[1]),
          timeoutMs: dco_decode_u_64(raw[2]),
        );
      case 9:
        return MinosError_CliProbeFailed(
          bin: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 10:
        return MinosError_RpcCallFailed(
          method: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 11:
        return MinosError_Unauthorized(reason: dco_decode_String(raw[1]));
      case 12:
        return MinosError_ConnectionStateMismatch(
          expected: dco_decode_String(raw[1]),
          actual: dco_decode_String(raw[2]),
        );
      case 13:
        return MinosError_EnvelopeVersionUnsupported(
          version: dco_decode_u_8(raw[1]),
        );
      case 14:
        return MinosError_PeerOffline(peerDeviceId: dco_decode_String(raw[1]));
      case 15:
        return MinosError_RelayInternal(message: dco_decode_String(raw[1]));
      case 16:
        return MinosError_CodexSpawnFailed(message: dco_decode_String(raw[1]));
      case 17:
        return MinosError_CodexConnectFailed(
          url: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 18:
        return MinosError_CodexProtocolError(
          method: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 19:
        return MinosError_AgentAlreadyRunning();
      case 20:
        return MinosError_AgentNotRunning();
      case 21:
        return MinosError_AgentNotSupported(
          agent: dco_decode_agent_name(raw[1]),
        );
      case 22:
        return MinosError_AgentSessionIdMismatch();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PairResponse dco_decode_pair_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PairResponse(
      ok: dco_decode_bool(arr[0]),
      macName: dco_decode_String(arr[1]),
    );
  }

  @protected
  PairingState dco_decode_pairing_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PairingState.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MobileClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MobileClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MobileClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<ConnectionState> sse_decode_StreamSink_connection_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentName sse_decode_agent_name(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AgentName.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ConnectionState_Disconnected();
      case 1:
        return ConnectionState_Pairing();
      case 2:
        return ConnectionState_Connected();
      case 3:
        var var_attempt = sse_decode_u_32(deserializer);
        return ConnectionState_Reconnecting(attempt: var_attempt);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ErrorKind sse_decode_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ErrorKind.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Lang sse_decode_lang(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Lang.values[inner];
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MinosError sse_decode_minos_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_addr = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_BindFailed(addr: var_addr, message: var_message);
      case 1:
        var var_url = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_ConnectFailed(url: var_url, message: var_message);
      case 2:
        var var_reason = sse_decode_String(deserializer);
        return MinosError_Disconnected(reason: var_reason);
      case 3:
        return MinosError_PairingTokenInvalid();
      case 4:
        var var_actual = sse_decode_pairing_state(deserializer);
        return MinosError_PairingStateMismatch(actual: var_actual);
      case 5:
        var var_deviceId = sse_decode_String(deserializer);
        return MinosError_DeviceNotTrusted(deviceId: var_deviceId);
      case 6:
        var var_path = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_StoreIo(path: var_path, message: var_message);
      case 7:
        var var_path = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_StoreCorrupt(path: var_path, message: var_message);
      case 8:
        var var_bin = sse_decode_String(deserializer);
        var var_timeoutMs = sse_decode_u_64(deserializer);
        return MinosError_CliProbeTimeout(
          bin: var_bin,
          timeoutMs: var_timeoutMs,
        );
      case 9:
        var var_bin = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_CliProbeFailed(bin: var_bin, message: var_message);
      case 10:
        var var_method = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_RpcCallFailed(
          method: var_method,
          message: var_message,
        );
      case 11:
        var var_reason = sse_decode_String(deserializer);
        return MinosError_Unauthorized(reason: var_reason);
      case 12:
        var var_expected = sse_decode_String(deserializer);
        var var_actual = sse_decode_String(deserializer);
        return MinosError_ConnectionStateMismatch(
          expected: var_expected,
          actual: var_actual,
        );
      case 13:
        var var_version = sse_decode_u_8(deserializer);
        return MinosError_EnvelopeVersionUnsupported(version: var_version);
      case 14:
        var var_peerDeviceId = sse_decode_String(deserializer);
        return MinosError_PeerOffline(peerDeviceId: var_peerDeviceId);
      case 15:
        var var_message = sse_decode_String(deserializer);
        return MinosError_RelayInternal(message: var_message);
      case 16:
        var var_message = sse_decode_String(deserializer);
        return MinosError_CodexSpawnFailed(message: var_message);
      case 17:
        var var_url = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_CodexConnectFailed(
          url: var_url,
          message: var_message,
        );
      case 18:
        var var_method = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MinosError_CodexProtocolError(
          method: var_method,
          message: var_message,
        );
      case 19:
        return MinosError_AgentAlreadyRunning();
      case 20:
        return MinosError_AgentNotRunning();
      case 21:
        var var_agent = sse_decode_agent_name(deserializer);
        return MinosError_AgentNotSupported(agent: var_agent);
      case 22:
        return MinosError_AgentSessionIdMismatch();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PairResponse sse_decode_pair_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_macName = sse_decode_String(deserializer);
    return PairResponse(ok: var_ok, macName: var_macName);
  }

  @protected
  PairingState sse_decode_pairing_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PairingState.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    MobileClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MobileClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    MobileClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MobileClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileClient(
    MobileClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MobileClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_connection_state_Sse(
    RustStreamSink<ConnectionState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_name(AgentName self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ConnectionState_Disconnected():
        sse_encode_i_32(0, serializer);
      case ConnectionState_Pairing():
        sse_encode_i_32(1, serializer);
      case ConnectionState_Connected():
        sse_encode_i_32(2, serializer);
      case ConnectionState_Reconnecting(attempt: final attempt):
        sse_encode_i_32(3, serializer);
        sse_encode_u_32(attempt, serializer);
    }
  }

  @protected
  void sse_encode_error_kind(ErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_lang(Lang self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_minos_error(MinosError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MinosError_BindFailed(addr: final addr, message: final message):
        sse_encode_i_32(0, serializer);
        sse_encode_String(addr, serializer);
        sse_encode_String(message, serializer);
      case MinosError_ConnectFailed(url: final url, message: final message):
        sse_encode_i_32(1, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(message, serializer);
      case MinosError_Disconnected(reason: final reason):
        sse_encode_i_32(2, serializer);
        sse_encode_String(reason, serializer);
      case MinosError_PairingTokenInvalid():
        sse_encode_i_32(3, serializer);
      case MinosError_PairingStateMismatch(actual: final actual):
        sse_encode_i_32(4, serializer);
        sse_encode_pairing_state(actual, serializer);
      case MinosError_DeviceNotTrusted(deviceId: final deviceId):
        sse_encode_i_32(5, serializer);
        sse_encode_String(deviceId, serializer);
      case MinosError_StoreIo(path: final path, message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(message, serializer);
      case MinosError_StoreCorrupt(path: final path, message: final message):
        sse_encode_i_32(7, serializer);
        sse_encode_String(path, serializer);
        sse_encode_String(message, serializer);
      case MinosError_CliProbeTimeout(
        bin: final bin,
        timeoutMs: final timeoutMs,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_String(bin, serializer);
        sse_encode_u_64(timeoutMs, serializer);
      case MinosError_CliProbeFailed(bin: final bin, message: final message):
        sse_encode_i_32(9, serializer);
        sse_encode_String(bin, serializer);
        sse_encode_String(message, serializer);
      case MinosError_RpcCallFailed(
        method: final method,
        message: final message,
      ):
        sse_encode_i_32(10, serializer);
        sse_encode_String(method, serializer);
        sse_encode_String(message, serializer);
      case MinosError_Unauthorized(reason: final reason):
        sse_encode_i_32(11, serializer);
        sse_encode_String(reason, serializer);
      case MinosError_ConnectionStateMismatch(
        expected: final expected,
        actual: final actual,
      ):
        sse_encode_i_32(12, serializer);
        sse_encode_String(expected, serializer);
        sse_encode_String(actual, serializer);
      case MinosError_EnvelopeVersionUnsupported(version: final version):
        sse_encode_i_32(13, serializer);
        sse_encode_u_8(version, serializer);
      case MinosError_PeerOffline(peerDeviceId: final peerDeviceId):
        sse_encode_i_32(14, serializer);
        sse_encode_String(peerDeviceId, serializer);
      case MinosError_RelayInternal(message: final message):
        sse_encode_i_32(15, serializer);
        sse_encode_String(message, serializer);
      case MinosError_CodexSpawnFailed(message: final message):
        sse_encode_i_32(16, serializer);
        sse_encode_String(message, serializer);
      case MinosError_CodexConnectFailed(
        url: final url,
        message: final message,
      ):
        sse_encode_i_32(17, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(message, serializer);
      case MinosError_CodexProtocolError(
        method: final method,
        message: final message,
      ):
        sse_encode_i_32(18, serializer);
        sse_encode_String(method, serializer);
        sse_encode_String(message, serializer);
      case MinosError_AgentAlreadyRunning():
        sse_encode_i_32(19, serializer);
      case MinosError_AgentNotRunning():
        sse_encode_i_32(20, serializer);
      case MinosError_AgentNotSupported(agent: final agent):
        sse_encode_i_32(21, serializer);
        sse_encode_agent_name(agent, serializer);
      case MinosError_AgentSessionIdMismatch():
        sse_encode_i_32(22, serializer);
    }
  }

  @protected
  void sse_encode_pair_response(PairResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.macName, serializer);
  }

  @protected
  void sse_encode_pairing_state(PairingState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class MobileClientImpl extends RustOpaque implements MobileClient {
  // Not to be used by end users
  MobileClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MobileClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MobileClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MobileClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MobileClientPtr,
  );

  /// Current connection state, read from the watch-channel cache. Cheap and
  /// synchronous.
  ConnectionState currentState() =>
      RustLib.instance.api.crateApiMinosMobileClientCurrentState(that: this);

  /// Pair using the raw JSON payload extracted from the scanned QR code.
  /// Delegates to `MobileClient::pair_with_json`; see that method for the
  /// full error surface.
  Future<PairResponse> pairWithJson({required String qrJson}) => RustLib
      .instance
      .api
      .crateApiMinosMobileClientPairWithJson(that: this, qrJson: qrJson);

  /// Subscribe to connection-state transitions. Emits the current value
  /// immediately, then every subsequent change. The spawned task exits once
  /// the Dart side drops the stream (detected via `sink.add(...).is_err()`).
  Stream<ConnectionState> subscribeState() =>
      RustLib.instance.api.crateApiMinosMobileClientSubscribeState(that: this);
}
