//! `gen-codex-protocol` xtask: regenerate the typed Rust mirror of the codex
//! app-server JSON schemas in `crates/minos-codex-protocol/src/generated/`.
//!
//! Pipeline: typify pass over `schemas/` → union post-processor over the four
//! oneOf union schemas → `cargo fmt -p minos-codex-protocol` → `cargo build`
//! to verify the result compiles.

use std::path::Path;

use anyhow::{Context, Result};

pub fn run(workspace_root: &Path) -> Result<()> {
    eprintln!("==> gen-codex-protocol: typify pass");
    typify_pass(workspace_root).context("typify pass")?;

    eprintln!("==> gen-codex-protocol: union post-processor");
    union_post_process(workspace_root).context("union post-processor")?;

    eprintln!("==> gen-codex-protocol: cargo fmt -p minos-codex-protocol");
    crate::run(
        "cargo",
        &["fmt", "-p", "minos-codex-protocol"],
        workspace_root,
    )?;

    eprintln!("==> gen-codex-protocol: cargo build -p minos-codex-protocol (verify)");
    crate::run(
        "cargo",
        &["build", "-p", "minos-codex-protocol"],
        workspace_root,
    )?;

    eprintln!("OK: minos-codex-protocol regenerated");
    Ok(())
}

fn typify_pass(workspace_root: &Path) -> Result<()> {
    use std::fs;
    use typify::{TypeSpace, TypeSpaceSettings};

    let schemas_dir = workspace_root.join("schemas");
    let v2_root = schemas_dir.join("codex_app_server_protocol.v2.schemas.json");
    let v1_root = schemas_dir.join("codex_app_server_protocol.schemas.json");

    let mut settings = TypeSpaceSettings::default();
    settings
        .with_struct_builder(false)
        .with_derive("PartialEq".into());
    // Note: `Eq` is intentionally omitted — at least one schema struct
    // (`McpElicitationNumberSchema`) carries an `Option<f64>` field, and
    // `f64` is not `Eq`. Adding `Eq` to the global typify settings would
    // refuse to compile the whole module.
    let mut type_space = TypeSpace::new(&settings);

    // The v1 root and v2 root schemas overlap on ~12 definitions
    // (`InitializeParams`, `ClientInfo`, `AbsolutePathBuf`, etc.). Feeding
    // both via `add_root_schema` separately produces byte-identical duplicate
    // structs that fail to compile. We merge them in memory: the v1 root
    // already nests the entire v2 namespace under `#/definitions/v2/`, but
    // typify cannot resolve `$ref` paths into nested namespaces, so we hoist
    // the v2 sub-namespace contents to the top level (under their plain
    // names) and rewrite v1's `#/definitions/v2/X` $refs to `#/definitions/X`.
    // Then we drop v1's `v2` sub-namespace and add the merged result once.
    let v1_raw =
        fs::read_to_string(&v1_root).with_context(|| format!("read {}", v1_root.display()))?;
    let _ = v2_root; // kept on disk for future direct introspection (e.g. tests)
    let merged_text = merge_v1_v2_schemas(&v1_raw)
        .with_context(|| format!("merge v1+v2 from {}", v1_root.display()))?;
    let schema: schemars::schema::RootSchema =
        serde_json::from_str(&merged_text).context("parse merged schema")?;
    type_space
        .add_root_schema(schema)
        .context("typify add_root_schema (merged v1+v2)")?;

    let tokens = type_space.to_stream();
    let parsed: syn::File = syn::parse2(tokens).context("syn parse typify output")?;
    let body = prettyplease::unparse(&parsed);

    // Typify emits `ServerRequest`, `ServerNotification`, `ClientRequest` and
    // `ClientNotification` enums whose variants carry `(id, method, params)`
    // tuples (or unit variants for paramless arms) — different shape from the
    // post-processor-generated `methods::ServerRequest` / `ServerNotification`
    // (which use `#[serde(tag = "method", content = "params")]`). The two
    // would clash when `lib.rs` glob-re-exports both modules. Rename the
    // typify versions to `*Raw` so both shapes coexist; the post-processor's
    // tagged-enum shape is the canonical crate-root surface.
    let body = rename_typify_union_collisions(&body);

    let out_path = workspace_root.join("crates/minos-codex-protocol/src/generated/types.rs");
    fs::create_dir_all(out_path.parent().unwrap())
        .with_context(|| format!("mkdir {}", out_path.parent().unwrap().display()))?;

    // Typify writes fully-qualified `::serde::Deserialize` / `::serde::Serialize`
    // attribute paths in every derive macro, so we deliberately do not import
    // serde at the top of the file — adding `use serde::...` would just produce
    // unused-import warnings.
    let banner = "\
// @generated by `cargo xtask gen-codex-protocol`. Do not edit by hand.
// Source schemas: schemas/codex_app_server_protocol.{v2.,}schemas.json
//
// Re-run `cargo xtask gen-codex-protocol` after touching schemas/ to refresh.

#![allow(clippy::all, clippy::pedantic, clippy::restriction, dead_code)]
#![allow(non_camel_case_types, non_snake_case)]

";

    fs::write(&out_path, format!("{banner}{body}"))
        .with_context(|| format!("write {}", out_path.display()))?;
    eprintln!(
        "    wrote {} ({} bytes)",
        out_path.display(),
        banner.len() + body.len()
    );
    Ok(())
}

/// Merge the v1 root schema's `#/definitions` with its embedded
/// `#/definitions/v2` sub-namespace, hoisting the v2 entries to the top
/// level and rewriting any `$ref: "#/definitions/v2/X"` to
/// `$ref: "#/definitions/X"`. v1 entries take precedence on collision,
/// which is safe because the overlapping ~12 definitions are byte-identical
/// across the two namespaces.
fn merge_v1_v2_schemas(v1_raw: &str) -> Result<String> {
    use serde_json::Value;

    let mut root: Value = serde_json::from_str(v1_raw).context("parse v1 schema as json")?;
    let definitions = root
        .get_mut("definitions")
        .and_then(Value::as_object_mut)
        .context("v1 schema missing definitions object")?;

    let v2_subns = definitions
        .remove("v2")
        .context("v1 schema missing definitions.v2 sub-namespace")?;
    let v2_subns = match v2_subns {
        Value::Object(map) => map,
        other => anyhow::bail!("v1 schema definitions.v2 expected object, got {other:?}"),
    };

    for (name, value) in v2_subns {
        // v1 entries (already in `definitions`) win on collision; the
        // overlapping definitions are structurally identical so this is safe.
        definitions.entry(name).or_insert(value);
    }

    // Now rewrite all `$ref: "#/definitions/v2/X"` to `$ref: "#/definitions/X"`.
    rewrite_v2_refs(&mut root);

    serde_json::to_string(&root).context("re-serialise merged schema")
}

fn rewrite_v2_refs(value: &mut serde_json::Value) {
    use serde_json::Value;
    match value {
        Value::Object(map) => {
            for (k, v) in map.iter_mut() {
                if k == "$ref" {
                    if let Value::String(s) = v {
                        if let Some(rest) = s.strip_prefix("#/definitions/v2/") {
                            *s = format!("#/definitions/{rest}");
                        }
                    }
                } else {
                    rewrite_v2_refs(v);
                }
            }
        }
        Value::Array(arr) => {
            for v in arr.iter_mut() {
                rewrite_v2_refs(v);
            }
        }
        _ => {}
    }
}

// `union_post_process` is intentionally one cohesive sequence — splitting it
// into per-enum helpers would obscure the parallel structure across the four
// schemas + four dispatch enums + impl blocks + synthetic markers.
#[allow(clippy::too_many_lines)]
fn union_post_process(workspace_root: &Path) -> Result<()> {
    use proc_macro2::TokenStream;
    use quote::{format_ident, quote};
    use std::collections::BTreeSet;
    use std::fs;

    let schemas_dir = workspace_root.join("schemas");

    let client_requests = parse_union_arms(&schemas_dir.join("ClientRequest.json"))?;
    let client_notifs = parse_union_arms(&schemas_dir.join("ClientNotification.json"))?;
    let server_requests = parse_union_arms(&schemas_dir.join("ServerRequest.json"))?;
    let server_notifs = parse_union_arms(&schemas_dir.join("ServerNotification.json"))?;

    // Read the typify-generated types.rs to detect which `*Params` /
    // `*Response` / `*Notification` structs already exist. Anything we
    // synthesise must not collide with a typify-generated definition.
    let types_path = workspace_root.join("crates/minos-codex-protocol/src/generated/types.rs");
    let types_src = fs::read_to_string(&types_path)
        .with_context(|| format!("read {} (run typify pass first)", types_path.display()))?;
    let existing_types = collect_existing_type_names(&types_src);

    // Collect which params/response struct names need synthesising.
    // Some arms reuse the same synthesised name across the union (unlikely,
    // but BTreeSet keeps it idempotent).
    let mut synthetic_params: BTreeSet<String> = BTreeSet::new();
    let mut synthetic_responses: BTreeSet<String> = BTreeSet::new();

    let mut out = TokenStream::new();

    // 1. impl ClientRequest for each. The Response type is derived from the
    // Params name by the standard naming convention `XxxParams ->
    // XxxResponse`. If neither exists we synthesise both as unit-like marker
    // structs serialised as JSON `null` — matching the schema's
    // `params: { type: "null" }` / `result: true` semantics.
    for arm in &client_requests {
        let method = &arm.method;
        let params_ty = &arm.params_ty;
        let response_ty = params_ty
            .strip_suffix("Params")
            .map(|stem| format!("{stem}Response"))
            .with_context(|| {
                format!(
                    "ClientRequest method `{method}`: expected params type `{params_ty}` to end in 'Params'"
                )
            })?;

        if arm.needs_synthetic_params && !existing_types.contains(params_ty) {
            synthetic_params.insert(params_ty.clone());
        }
        if !existing_types.contains(&response_ty) {
            // No typify-generated `XxxResponse` — emit a unit-like marker.
            // This catches the few methods that respond with `null`
            // (e.g. `account/logout`).
            synthetic_responses.insert(response_ty.clone());
        }

        let params_ident = format_ident!("{}", params_ty);
        let response_ident = format_ident!("{}", response_ty);
        out.extend(quote! {
            impl crate::ClientRequest for #params_ident {
                const METHOD: &'static str = #method;
                type Response = #response_ident;
            }
        });
    }

    // 2. impl ClientNotification for each. Most notifications carry no
    // params; for the lone `initialized` arm typify does NOT emit a struct
    // (the schema's only `properties` is `method`), so we synthesise an
    // `InitializedNotification` marker.
    for arm in &client_notifs {
        let params_ty = &arm.params_ty;
        if arm.needs_synthetic_params && !existing_types.contains(params_ty) {
            synthetic_params.insert(params_ty.clone());
        }
        let method = &arm.method;
        let params_ident = format_ident!("{}", params_ty);
        out.extend(quote! {
            impl crate::ClientNotification for #params_ident {
                const METHOD: &'static str = #method;
            }
        });
    }

    // 3. ServerRequest enum — one variant per schema arm.
    let server_request_variants = server_requests.iter().map(|arm| {
        let method = &arm.method;
        let variant = format_ident!("{}", variant_name_from_params(&arm.params_ty));
        let params_ident = format_ident!("{}", &arm.params_ty);
        quote! {
            #[serde(rename = #method)]
            #variant(#params_ident),
        }
    });
    out.extend(quote! {
        #[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
        #[serde(tag = "method", content = "params")]
        pub enum ServerRequest {
            #(#server_request_variants)*
        }
    });

    // 4. ServerNotification enum.
    let server_notif_variants = server_notifs.iter().map(|arm| {
        let method = &arm.method;
        let variant = format_ident!("{}", variant_name_from_params(&arm.params_ty));
        let params_ident = format_ident!("{}", &arm.params_ty);
        quote! {
            #[serde(rename = #method)]
            #variant(#params_ident),
        }
    });
    out.extend(quote! {
        #[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
        #[serde(tag = "method", content = "params")]
        pub enum ServerNotification {
            #(#server_notif_variants)*
        }
    });

    // 5. ClientRequestMethod enum (mirror; downstream may not use it but keeps
    // the symmetry and provides serde-driven dispatch for tooling/replay).
    let client_request_variants = client_requests.iter().map(|arm| {
        let method = &arm.method;
        let variant = format_ident!("{}", variant_name_from_params(&arm.params_ty));
        let params_ident = format_ident!("{}", &arm.params_ty);
        quote! {
            #[serde(rename = #method)]
            #variant(#params_ident),
        }
    });
    out.extend(quote! {
        #[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
        #[serde(tag = "method", content = "params")]
        pub enum ClientRequestMethod {
            #(#client_request_variants)*
        }
    });

    // 6. ClientNotificationMethod enum.
    let client_notif_variants = client_notifs.iter().map(|arm| {
        let method = &arm.method;
        let variant = format_ident!("{}", variant_name_from_params(&arm.params_ty));
        let params_ident = format_ident!("{}", &arm.params_ty);
        quote! {
            #[serde(rename = #method)]
            #variant(#params_ident),
        }
    });
    out.extend(quote! {
        #[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
        #[serde(tag = "method", content = "params")]
        pub enum ClientNotificationMethod {
            #(#client_notif_variants)*
        }
    });

    // 7. Synthetic params/response marker structs. Unit structs serialise
    // to JSON `null`, matching the schema's `params: { type: "null" }` and
    // implicit-null response shapes for paramless / result-less methods.
    let mut synthetic_tokens = TokenStream::new();
    for name in synthetic_params.iter().chain(synthetic_responses.iter()) {
        let ident = format_ident!("{}", name);
        synthetic_tokens.extend(quote! {
            /// Synthesised marker for a JSON-RPC method whose schema declares
            /// `params: { type: "null" }` (or no params) and/or no response
            /// payload. Serialises as JSON `null`.
            #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Deserialize, serde::Serialize)]
            pub struct #ident;
        });
    }

    let parsed: syn::File = syn::parse2(quote! { #synthetic_tokens #out })
        .context("syn parse post-processor output")?;
    let body = prettyplease::unparse(&parsed);

    let banner = "\
// @generated by `cargo xtask gen-codex-protocol` post-processor. Do not edit.
// Source: schemas/{ClientRequest,ClientNotification,ServerRequest,ServerNotification}.json
//
// One impl ClientRequest / impl ClientNotification per oneOf arm, plus the
// four tagged-enum dispatch types and any synthetic marker structs needed
// for paramless / result-less methods.

#![allow(clippy::all, clippy::pedantic, clippy::restriction)]

use crate::generated::types::*;

";

    let out_path = workspace_root.join("crates/minos-codex-protocol/src/generated/methods.rs");
    fs::write(&out_path, format!("{banner}{body}"))
        .with_context(|| format!("write {}", out_path.display()))?;
    eprintln!(
        "    wrote {} ({} bytes)",
        out_path.display(),
        banner.len() + body.len()
    );
    Ok(())
}

/// Rename the four typify-emitted top-level union enums that collide with
/// the post-processor's tagged-enum dispatch types and the hand-written
/// trait names. We append `Raw` to disambiguate; the canonical crate-root
/// `ServerRequest` etc. live in `generated::methods`.
fn rename_typify_union_collisions(body: &str) -> String {
    // Order matters: longer names first so `ClientNotification` doesn't
    // accidentally rewrite `ClientNotificationFoo`. We walk word boundaries
    // ourselves rather than use regex (xtask deps are minimal).
    const COLLISIONS: &[&str] = &[
        "ClientNotification",
        "ClientRequest",
        "ServerNotification",
        "ServerRequest",
    ];
    let mut out = String::with_capacity(body.len());
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let mut matched = None;
        for needle in COLLISIONS {
            let n = needle.len();
            if i + n > bytes.len() {
                continue;
            }
            if &body[i..i + n] != *needle {
                continue;
            }
            // Ensure word boundary on both sides.
            let prev_ok = i == 0 || !is_ident_continue(bytes[i - 1]);
            let next_ok = i + n == bytes.len() || !is_ident_continue(bytes[i + n]);
            if prev_ok && next_ok {
                matched = Some(*needle);
                break;
            }
        }
        if let Some(needle) = matched {
            out.push_str(needle);
            out.push_str("Raw");
            i += needle.len();
        } else {
            // SAFETY: i is a UTF-8 boundary because we only advance via
            // `body[i..]` slice operations above, which Rust panics on if
            // not on a boundary, or via 1-byte ASCII increments here.
            let ch = body[i..].chars().next().unwrap();
            out.push(ch);
            i += ch.len_utf8();
        }
    }
    out
}

fn is_ident_continue(b: u8) -> bool {
    matches!(b, b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'_')
}

/// Scan the typify-generated `types.rs` source and collect every `pub
/// struct` and `pub enum` name. Used by the union post-processor to decide
/// which marker structs to synthesise without colliding with typify's
/// output.
fn collect_existing_type_names(src: &str) -> std::collections::BTreeSet<String> {
    let mut out = std::collections::BTreeSet::new();
    for line in src.lines() {
        let line = line.trim_start();
        for prefix in ["pub struct ", "pub enum "] {
            if let Some(rest) = line.strip_prefix(prefix) {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    out.insert(name);
                }
            }
        }
    }
    out
}

/// One arm of a `oneOf` union schema, normalised for codegen.
struct UnionArm {
    method: String,
    /// Rust identifier for the params struct. For `params: { $ref }` we strip
    /// the `#/definitions/` prefix. For `params: { type: "null" }` (no
    /// referenced struct), we synthesise an identifier from the method name.
    params_ty: String,
    /// True when the schema arm declares `params: { type: "null" }` (or no
    /// `params` field at all) and there is no existing `*Params` /
    /// `*Notification` typify-generated struct, so we must synthesise a
    /// unit-like marker struct in `methods.rs`.
    needs_synthetic_params: bool,
}

/// Parse one union schema (`ClientRequest.json` etc.) and return one
/// `UnionArm` per arm. Each arm has shape
/// `{ method: { enum: ["xxx"] }, params: { $ref: "#/definitions/XxxParams" } }`
/// for the common case, or `params: { type: "null" }` / no params field at
/// all for "no params" methods. For "no params" arms we prefer the arm's
/// `title` (a clean identifier like `InitializedNotification`) and fall
/// back to synthesising one from the method when the title contains
/// characters invalid in Rust idents (e.g. `Account/logoutRequest`).
fn parse_union_arms(path: &Path) -> Result<Vec<UnionArm>> {
    use std::fs;
    let raw = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let value: serde_json::Value =
        serde_json::from_str(&raw).with_context(|| format!("parse {}", path.display()))?;
    let arms = value
        .get("oneOf")
        .and_then(|v| v.as_array())
        .with_context(|| format!("{} missing top-level oneOf array", path.display()))?;
    let mut out = Vec::with_capacity(arms.len());
    for (i, arm) in arms.iter().enumerate() {
        let method = arm
            .pointer("/properties/method/enum/0")
            .and_then(|v| v.as_str())
            .with_context(|| {
                format!(
                    "{} arm {} missing properties.method.enum[0]",
                    path.display(),
                    i
                )
            })?
            .to_string();

        let params_ref = arm
            .pointer("/properties/params/$ref")
            .and_then(|v| v.as_str());

        let (params_ty, needs_synthetic_params) = if let Some(refstr) = params_ref {
            // "#/definitions/XxxParams" -> "XxxParams"
            (refstr.rsplit('/').next().unwrap().to_string(), false)
        } else {
            // No `$ref` — schema either declares `params: { type: "null" }`
            // or omits the `params` property entirely. We need a synthesised
            // marker struct.
            //
            // Prefer the arm's `title` when it's a clean Rust identifier
            // (e.g. `InitializedNotification`). When the title contains `/`
            // (e.g. `Account/logoutRequest`), it isn't a valid Rust ident, so
            // fall back to a name synthesised from the method.
            let title = arm.get("title").and_then(|v| v.as_str());
            let candidate = title.filter(|t| t.chars().all(is_rust_ident_char));
            let name = match candidate {
                Some(t) => t.to_string(),
                None => synthesise_params_ident(&method),
            };
            (name, true)
        };
        out.push(UnionArm {
            method,
            params_ty,
            needs_synthetic_params,
        });
    }
    Ok(out)
}

fn is_rust_ident_char(c: char) -> bool {
    c.is_alphanumeric() || c == '_'
}

/// Build a Rust identifier from a JSON-RPC method string, used when the
/// schema doesn't reference an existing `*Params` definition. Examples:
/// `"account/logout"` → `"AccountLogoutParams"`,
/// `"config/mcpServer/reload"` → `"ConfigMcpServerReloadParams"`.
fn synthesise_params_ident(method: &str) -> String {
    let mut out = String::new();
    for segment in method.split('/') {
        if segment.is_empty() {
            continue;
        }
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.extend(chars);
        }
    }
    format!("{out}Params")
}

/// `XxxParams` -> `Xxx`. `XxxNotification` -> `Xxx`. Used for enum variant
/// names so `ThreadStartParams` becomes `ServerRequest::ThreadStart(...)`-style
/// (or `ServerNotification::ThreadStarted(...)` for `ThreadStartedNotification`).
fn variant_name_from_params(params_ty: &str) -> String {
    if let Some(stem) = params_ty.strip_suffix("Params") {
        return stem.to_string();
    }
    if let Some(stem) = params_ty.strip_suffix("Notification") {
        return stem.to_string();
    }
    params_ty.to_string()
}
