#!/usr/bin/env python3
"""Lightweight sanity checker for Codex app-server JSON v2 JSONL examples.

This catches common protocol mistakes only. It is not a replacement for the
version-specific JSON Schema generated by `codex app-server generate-json-schema`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


def fail(path: Path, line_no: int, msg: str) -> int:
    print(f"{path}:{line_no}: {msg}", file=sys.stderr)
    return 1


def validate_message(path: Path, line_no: int, msg: Any) -> int:
    errors = 0
    if not isinstance(msg, dict):
        return fail(path, line_no, "message must be a JSON object")
    if "jsonrpc" in msg:
        errors += fail(path, line_no, 'do not include "jsonrpc" on the app-server wire protocol')
    has_method = "method" in msg
    has_id = "id" in msg
    has_result = "result" in msg
    has_error = "error" in msg
    if has_result and has_error:
        errors += fail(path, line_no, "response must not contain both result and error")
    if has_method:
        if not isinstance(msg["method"], str) or not msg["method"]:
            errors += fail(path, line_no, "method must be a non-empty string")
        if has_result or has_error:
            errors += fail(path, line_no, "request/notification must not include result or error")
    else:
        if not has_id:
            errors += fail(path, line_no, "response must include id")
        if not (has_result or has_error):
            errors += fail(path, line_no, "response must include result or error")
    if "params" in msg and msg["params"] is None:
        errors += fail(path, line_no, "prefer {} or omit params instead of null")
    return errors


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: validate_json_v2_messages.py <messages.jsonl>", file=sys.stderr)
        return 2
    path = Path(argv[1])
    total_errors = 0
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            try:
                msg = json.loads(stripped)
            except json.JSONDecodeError as exc:
                total_errors += fail(path, line_no, f"invalid JSON: {exc}")
                continue
            total_errors += validate_message(path, line_no, msg)
    if total_errors:
        print(f"failed with {total_errors} error(s)", file=sys.stderr)
        return 1
    print("ok: JSON v2 message sanity checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
