#!/usr/bin/env bash
# Merge legacy dual env files into the single VPS SSOT: minos.env
#
# Safe for production:
#   - never prints secret values
#   - backs up existing files with a timestamp
#   - prefers backend.env (live systemd binary) over compose .env for app keys
#   - pulls POSTGRES_* / MINOS_BACKEND_IMAGE from compose .env when missing
#   - leaves a .env symlink → minos.env for docker compose
#
# Usage (on VPS as root):
#   /opt/minos/bin/merge-minos-env.sh
#   /opt/minos/bin/merge-minos-env.sh --deploy-dir /opt/minos/deploy --dry-run
set -euo pipefail

DEPLOY_DIR="${MINOS_DEPLOY_DIR:-/opt/minos/deploy}"
DRY_RUN=0
APPLY_UNIT=1
RESTART=0

usage() {
  cat <<'EOF'
Merge backend.env + .env into minos.env (single VPS env SSOT).

Usage:
  merge-minos-env.sh [options]

Options:
  --deploy-dir DIR   Deploy directory (default: /opt/minos/deploy)
  --dry-run          Show planned actions; write nothing
  --no-unit          Do not rewrite systemd EnvironmentFile path
  --restart          systemctl restart minos-backend after merge
  -h, --help         Show this help

Result:
  minos.env          SSOT (mode 640 root:minos)
  .env               symlink → minos.env (compose variable file)
  backups under      deploy/env-backups/<timestamp>/
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deploy-dir)
      DEPLOY_DIR="${2:?}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --no-unit)
      APPLY_UNIT=0
      shift
      ;;
    --restart)
      RESTART=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "error: run as root (or sudo $0)" >&2
  exit 1
fi

MINOS_ENV="${DEPLOY_DIR}/minos.env"
LEGACY_BACKEND="${DEPLOY_DIR}/backend.env"
LEGACY_COMPOSE="${DEPLOY_DIR}/.env"
UNIT=/etc/systemd/system/minos-backend.service
TS="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR="${DEPLOY_DIR}/env-backups/${TS}"

echo "==> deploy dir: $DEPLOY_DIR"
echo "==> target:     $MINOS_ENV"

if [[ ! -d "$DEPLOY_DIR" ]]; then
  echo "error: missing deploy dir $DEPLOY_DIR" >&2
  exit 1
fi

# Prefer live binary env as app base; fall back to compose .env.
BASE=""
if [[ -f "$LEGACY_BACKEND" && ! -L "$LEGACY_BACKEND" ]]; then
  BASE="$LEGACY_BACKEND"
  echo "==> base keys from backend.env (systemd binary path)"
elif [[ -f "$MINOS_ENV" && ! -L "$MINOS_ENV" ]]; then
  BASE="$MINOS_ENV"
  echo "==> base keys from existing minos.env"
elif [[ -f "$LEGACY_COMPOSE" && ! -L "$LEGACY_COMPOSE" ]]; then
  BASE="$LEGACY_COMPOSE"
  echo "==> base keys from .env (compose only)"
else
  echo "error: no backend.env, minos.env, or regular .env to merge" >&2
  exit 1
fi

COMPOSE_SRC=""
if [[ -f "$LEGACY_COMPOSE" && ! -L "$LEGACY_COMPOSE" && "$LEGACY_COMPOSE" != "$BASE" ]]; then
  COMPOSE_SRC="$LEGACY_COMPOSE"
  echo "==> overlay compose-only keys from .env"
fi

# Keys that typically live only in compose .env and should be filled if missing.
OVERLAY_KEYS=(
  POSTGRES_USER
  POSTGRES_PASSWORD
  POSTGRES_DB
  MINOS_BACKEND_IMAGE
)

extract_key() {
  # $1=file $2=key → value without export/quotes (best-effort; no print of value by callers)
  local file="$1" key="$2" line
  line="$(grep -E "^[[:space:]]*(export[[:space:]]+)?${key}=" "$file" 2>/dev/null | tail -n1 || true)"
  [[ -n "$line" ]] || return 1
  line="${line#export }"
  line="${line#"${key}="}"
  # strip surrounding single/double quotes
  if [[ "$line" == \"*\" && "$line" == *\" ]]; then
    line="${line:1:${#line}-2}"
  elif [[ "$line" == \'*\' && "$line" == *\' ]]; then
    line="${line:1:${#line}-2}"
  fi
  printf '%s' "$line"
}

has_key() {
  local file="$1" key="$2"
  grep -Eq "^[[:space:]]*(export[[:space:]]+)?${key}=" "$file" 2>/dev/null
}

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[dry-run] would backup existing env files → $BACKUP_DIR"
  echo "[dry-run] would write $MINOS_ENV from $BASE (+ overlay keys if missing)"
  echo "[dry-run] would symlink $LEGACY_COMPOSE → minos.env"
  if [[ -f "$LEGACY_BACKEND" && ! -L "$LEGACY_BACKEND" ]]; then
    echo "[dry-run] would leave backend.env as timestamped backup only (not deleted raw until backup)"
  fi
  if [[ "$APPLY_UNIT" -eq 1 && -f "$UNIT" ]]; then
    echo "[dry-run] would rewrite EnvironmentFile in $UNIT to minos.env"
  fi
  exit 0
fi

mkdir -p "$BACKUP_DIR"
for f in "$LEGACY_BACKEND" "$LEGACY_COMPOSE" "$MINOS_ENV"; do
  if [[ -e "$f" && ! -L "$f" ]]; then
    cp -a "$f" "$BACKUP_DIR/$(basename "$f")"
    echo "    backed up $(basename "$f")"
  elif [[ -L "$f" ]]; then
    readlink "$f" >"$BACKUP_DIR/$(basename "$f").symlink" || true
    echo "    recorded symlink $(basename "$f") → $(readlink "$f" || true)"
  fi
done

tmp="$(mktemp)"
# Header
{
  echo "# Generated by merge-minos-env.sh at ${TS}"
  echo "# Single VPS env SSOT. Edit this file only; .env is a symlink here."
  echo "# systemd EnvironmentFile does not expand \${VAR} — keep DB password lines in sync."
  echo
  cat "$BASE"
} >"$tmp"

# Overlay missing compose keys
if [[ -n "$COMPOSE_SRC" ]]; then
  for key in "${OVERLAY_KEYS[@]}"; do
    if has_key "$tmp" "$key"; then
      continue
    fi
    if val="$(extract_key "$COMPOSE_SRC" "$key")"; then
      printf '\n# overlay from legacy compose .env\n%s=%s\n' "$key" "$val" >>"$tmp"
      echo "    + added missing $key from compose .env"
    fi
  done
fi

# If POSTGRES_PASSWORD still missing, try to parse from MINOS_DATABASE_URL (postgres://user:pass@host/db)
if ! has_key "$tmp" POSTGRES_PASSWORD; then
  if dburl="$(extract_key "$tmp" MINOS_DATABASE_URL 2>/dev/null || true)"; then
    # crude parse: postgres://user:pass@host:port/db
    if [[ "$dburl" =~ ^postgres(ql)?://([^:/]+):([^@]+)@ ]]; then
      printf '\n# derived from MINOS_DATABASE_URL\nPOSTGRES_PASSWORD=%s\n' "${BASH_REMATCH[3]}" >>"$tmp"
      echo "    + derived POSTGRES_PASSWORD from MINOS_DATABASE_URL"
      if ! has_key "$tmp" POSTGRES_USER; then
        printf 'POSTGRES_USER=%s\n' "${BASH_REMATCH[2]}" >>"$tmp"
        echo "    + derived POSTGRES_USER from MINOS_DATABASE_URL"
      fi
    fi
  fi
fi

if ! has_key "$tmp" POSTGRES_DB; then
  printf '\nPOSTGRES_DB=minos\n' >>"$tmp"
  echo "    + defaulted POSTGRES_DB=minos"
fi

if ! has_key "$tmp" POSTGRES_USER; then
  printf '\nPOSTGRES_USER=minos\n' >>"$tmp"
  echo "    + defaulted POSTGRES_USER=minos"
fi

install -m 640 -o root -g minos "$tmp" "$MINOS_ENV"
rm -f "$tmp"
echo "==> wrote $MINOS_ENV (mode 640 root:minos)"

# Compose project file: symlink to SSOT
if [[ -e "$LEGACY_COMPOSE" || -L "$LEGACY_COMPOSE" ]]; then
  rm -f "$LEGACY_COMPOSE"
fi
ln -sfn "$MINOS_ENV" "$LEGACY_COMPOSE"
echo "==> linked $LEGACY_COMPOSE → $MINOS_ENV"

# Retire backend.env as a pointer file (real content is in backup + minos.env)
if [[ -f "$LEGACY_BACKEND" || -L "$LEGACY_BACKEND" ]]; then
  rm -f "$LEGACY_BACKEND"
  cat >"$LEGACY_BACKEND" <<EOF
# Deprecated. Single SSOT is:
#   ${MINOS_ENV}
# This stub exists so old scripts fail loudly with a readable message.
# Backup of previous file: ${BACKUP_DIR}/
EOF
  chmod 644 "$LEGACY_BACKEND"
  echo "==> replaced backend.env with deprecation stub (backup under $BACKUP_DIR)"
fi

if [[ "$APPLY_UNIT" -eq 1 && -f "$UNIT" ]]; then
  if grep -q 'EnvironmentFile=.*backend\.env' "$UNIT" 2>/dev/null \
    || ! grep -q 'EnvironmentFile=.*minos\.env' "$UNIT" 2>/dev/null; then
    sed -i.bak-envmerge \
      -e "s|EnvironmentFile=.*/backend\.env|EnvironmentFile=${MINOS_ENV}|g" \
      -e "s|EnvironmentFile=/opt/minos/deploy/backend.env|EnvironmentFile=${MINOS_ENV}|g" \
      "$UNIT"
    # If unit still has no minos.env line, force-set common path
    if ! grep -q 'EnvironmentFile=.*minos\.env' "$UNIT"; then
      if grep -q '^EnvironmentFile=' "$UNIT"; then
        sed -i 's|^EnvironmentFile=.*|EnvironmentFile='"${MINOS_ENV}"'|' "$UNIT"
      else
        sed -i '/^\[Service\]/a EnvironmentFile='"${MINOS_ENV}" "$UNIT"
      fi
    fi
    systemctl daemon-reload
    echo "==> unit EnvironmentFile → $MINOS_ENV (daemon-reload done)"
  else
    echo "==> unit already points at minos.env"
  fi
fi

# Key presence check (names only)
echo "==> key presence (names only):"
for key in \
  POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB \
  MINOS_BACKEND_LISTEN MINOS_DATABASE_URL MINOS_REDIS_URL \
  MINOS_JWT_SECRET MINOS_ENV MINOS_CORS_ORIGINS \
  MINOS_CACHE_BACKEND MINOS_MESSAGE_BUS_BACKEND \
  SUPABASE_URL MINOS_R2_BUCKET
do
  if has_key "$MINOS_ENV" "$key"; then
    echo "    OK  $key"
  else
    echo "    --  $key (absent)"
  fi
done

if [[ "$RESTART" -eq 1 ]]; then
  echo "==> restart minos-backend"
  systemctl restart minos-backend
  systemctl --no-pager --full status minos-backend || true
fi

echo "==> merge complete"
echo "    SSOT:    $MINOS_ENV"
echo "    compose: $LEGACY_COMPOSE → minos.env"
echo "    backup:  $BACKUP_DIR"
echo "    restart: systemctl restart minos-backend   # required to load new EnvironmentFile"
