// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'minos.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `frb_runtime`, `parse_device_id`, `spawn_state_forwarder`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StartAgentResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initialize mobile-side Rust logging with the given directory (supplied by
/// Dart, typically `<Documents>/Minos/Logs`). Idempotent — safe to call once
/// per launch.
Future<void> initLogging({required String logDir}) =>
    RustLib.instance.api.crateApiMinosInitLogging(logDir: logDir);

/// Localize an `ErrorKind` into user-facing copy. Mirrors the UniFFI adapter's
/// `kind_message` so Dart can render localized error strings without hard-
/// coding them.
String kindMessage({required ErrorKind kind, required Lang lang}) =>
    RustLib.instance.api.crateApiMinosKindMessage(kind: kind, lang: lang);

void emitLog({
  required LogLevel level,
  required String target,
  required String message,
}) => RustLib.instance.api.crateApiMinosEmitLog(
  level: level,
  target: target,
  message: message,
);

/// Snapshot the records currently held in the ring buffer (oldest first).
/// Pair this with [`subscribe_log_records`] when populating a freshly
/// mounted log panel so prior events are not lost.
List<LogRecord> recentLogRecords() =>
    RustLib.instance.api.crateApiMinosRecentLogRecords();

/// Subscribe to the live tail. Each subscriber gets its own broadcast
/// receiver; lagging subscribers drop old records (the producer is never
/// blocked). The spawned task exits when the Dart side drops the stream.
Stream<LogRecord> subscribeLogRecords() =>
    RustLib.instance.api.crateApiMinosSubscribeLogRecords();

List<RequestTraceRecord> recentRequestTraces() =>
    RustLib.instance.api.crateApiMinosRecentRequestTraces();

void clearRequestTraces() =>
    RustLib.instance.api.crateApiMinosClearRequestTraces();

Stream<RequestTraceRecord> subscribeRequestTraces() =>
    RustLib.instance.api.crateApiMinosSubscribeRequestTraces();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>
abstract class MobileClient implements RustOpaqueInterface {
  Future<FriendRequestSummary> acceptFriendRequest({required String requestId});

  /// Read the current active Mac id, or `None` if no pair has been
  /// completed yet.
  Future<String?> activeHost();

  Future<void> addAgentToConversation({
    required String conversationId,
    required String agentId,
  });

  Future<void> addGroupMember({
    required String conversationId,
    required String memberAccountId,
  });

  /// Permanently close the given thread. Idempotent.
  Future<void> closeSession({required String sessionId});

  Future<ConversationMembersResponse> conversationMembers({
    required String conversationId,
  });

  Future<ConversationsResponse> conversations();

  Future<FriendRequestSummary> createFriendRequest({
    required String targetMinosId,
  });

  Future<ConversationResponse> createGroupConversation({
    required String title,
    required List<String> memberAccountIds,
  });

  /// Create a new project on the daemon.
  Future<CreateProjectResponse> createProject({
    required CreateProjectRequest req,
  });

  /// Current connection state, read from the watch-channel cache. Cheap and
  /// synchronous.
  ConnectionState currentState();

  Future<void> deleteConversation({required String conversationId});

  /// Delete a project.
  Future<void> deleteProject({required DeleteProjectRequest req});

  Future<ConversationResponse> ensureDirectConversation({
    required String friendAccountId,
  });

  /// Unlink a host installation from the account and clear local active-host
  /// when it matches. Idempotent.
  Future<void> forgetHost({required String hostDeviceId});

  Future<FriendRequestsResponse> friendRequests();

  Future<FriendsResponse> friends();

  /// Pause an in-flight turn on the given thread. Best-effort. The thread
  /// transitions to `Suspended { UserInterrupt }` regardless of whether the
  /// codex side acknowledges in time.
  Future<void> interruptSession({required String sessionId});

  Future<List<AgentSessionSummaryDto>> listAgentSessions({
    String? conversationId,
    required int limit,
  });

  Future<ListAgentsResponse> listAgents();

  Future<ListChatMessagesResponse> listChatMessages({
    required String conversationId,
    PlatformInt64? beforeSeq,
    PlatformInt64? afterSeq,
    required int limit,
  });

  /// Detect the CLI agents available on the paired runtime.
  Future<List<AgentDescriptor>> listClis();

  Future<ConversationAgentMembersResponse> listConversationAgents({
    required String conversationId,
  });

  /// Scan host-side skills for the selected runtime host.
  Future<ListHostSkillsResponse> listHostSkills({
    String? hostDeviceId,
    required bool forceReload,
  });

  Future<ListHostWorkspacesResponse> listHostWorkspaces({
    String? hostDeviceId,
    String? root,
    required int limit,
  });

  /// List every Mac linked to the caller's account (`GET /v1/hosts`).
  Future<List<HostSummaryDto>> listPairedHosts();

  /// List sessions within a project.
  Future<ListProjectSessionsResponse> listProjectSessions({
    required ListProjectSessionsParams req,
  });

  /// List all projects on the daemon.
  Future<ListProjectsResponse> listProjects();

  /// Request a page of thread summaries.
  Future<ListSessionsResponse> listSessions({required ListSessionsParams req});

  /// Exchange a Supabase access token for Minos access/refresh tokens and
  /// adopt the resulting session.
  Future<AuthSummary> loginWithSupabase({required String supabaseAccessToken});

  /// Log out of the current session. Best-effort `stop_agent`, then
  /// revoke the refresh token server-side, then wipe local state.
  Future<void> logout();

  Future<ConversationReadResponse> markConversationRead({
    required String conversationId,
  });

  Future<MyProfileResponse> myProfile();

  /// Construct a client backed by the built-in in-memory session store.
  /// Synchronous — no I/O happens until an auth/session method is called.
  factory MobileClient({required String selfName}) =>
      RustLib.instance.api.crateApiMinosMobileClientNew(selfName: selfName);

  /// Construct a client preloaded with a durable session snapshot from the
  /// Dart-side secure store.
  static MobileClient newWithPersistedState({
    required String selfName,
    required PersistedPairingState state,
  }) => RustLib.instance.api.crateApiMinosMobileClientNewWithPersistedState(
    selfName: selfName,
    state: state,
  );

  /// Mark the app as backgrounded. Pauses the reconnect loop so we
  /// don't poke the backend while the OS is freezing the process.
  void notifyBackgrounded();

  /// Mark the app as foregrounded. Resets the reconnect backoff so the
  /// next connect attempt happens promptly.
  void notifyForegrounded();

  /// Export the current pairing snapshot so Dart can mirror it into secure
  /// storage after pairing succeeds.
  Future<PersistedPairingState> persistedPairingState();

  /// Read a window of translated UI events for one session.
  Future<ReadSessionResponse> readSession({required ReadSessionParams req});

  Future<ChatMessageSummary> recallChatMessage({
    required String conversationId,
    required String messageId,
  });

  /// Rotate the bearer + refresh tokens. Surfaces `Refreshing` /
  /// `Authenticated` / `RefreshFailed` transitions on the auth-state
  /// stream.
  Future<void> refreshSession();

  Future<AgentSummary> registerAgent({
    required String name,
    required String description,
    required String runtimeAgent,
    required String model,
    String? workspacePath,
  });

  Future<FriendRequestSummary> rejectFriendRequest({required String requestId});

  Future<void> removeAgentFromConversation({
    required String conversationId,
    required String agentId,
  });

  Future<void> removeGroupMember({
    required String conversationId,
    required String memberAccountId,
  });

  /// Submit an opencode question answer for a pending host request.
  Future<void> respondOpencodeQuestion({
    required String sessionId,
    required String questionId,
    required String answersJson,
  });

  /// Reconnect using the durable session snapshot already loaded from the
  /// Dart-side secure store.
  Future<void> resumePersistedSession();

  Future<List<UserSummary>> searchUsers({required String minosId});

  /// Submit a user approval decision for a pending host request.
  ///
  /// `client_request_id` is the Hub Intent Outbox id (C5.3). When omitted,
  /// the mobile client generates one so the wire body never hardcodes null.
  Future<void> sendApprovalDecision({
    required String requestId,
    required String sessionId,
    required String decisionJson,
    String? clientRequestId,
  });

  Future<ChatMessageSummary> sendChatMessage({
    required String conversationId,
    required String text,
    String? replyToMessageId,
    String? clientMessageId,
  });

  /// Send a follow-up user message to an existing agent session.
  Future<void> sendUserMessage({
    required String sessionId,
    required String text,
  });

  /// Override the active Mac the next forward-RPC routes to.
  Future<void> setActiveHost({required String hostDeviceId});

  Future<MyProfileResponse> setMinosId({required String minosId});

  Future<void> subscribeAgentSession({required String sessionId});

  /// Subscribe to auth-state transitions. Emits the current cached frame
  /// immediately, then every subsequent change. The spawned task exits
  /// once Dart drops the stream (detected via `sink.add(...).is_err()`).
  Stream<AuthStateFrame> subscribeAuthState();

  /// Open-chat live path (R3a): subscribe `conversation:{id}` for full T1 frames.
  Future<void> subscribeConversation({required String conversationId});

  /// Subscribe to live `SocialEventFrame`s fanned out from the backend.
  Stream<SocialEventFrame> subscribeSocialEvents();

  /// Subscribe to connection-state transitions. Emits the current value
  /// immediately, then every subsequent change. The spawned task exits once
  /// the Dart side drops the stream (detected via `sink.add(...).is_err()`).
  Stream<ConnectionState> subscribeState();

  /// Subscribe to live `UiEventFrame`s fanned out from the backend.
  /// Every frb stream sink gets its own broadcast receiver; lagging
  /// subscribers lose old frames rather than blocking the producer.
  Stream<UiEventFrame> subscribeUiEvents();

  /// Toggle Hub reaction; `client_op_id` is the Intent Outbox id (B6/C5).
  Future<ToggleReactionResponse> toggleReaction({
    required String conversationId,
    required String messageId,
    required String emoji,
    required String clientOpId,
  });

  /// Leave open-chat conversation topic (R3a).
  Future<void> unsubscribeConversation({required String conversationId});

  Future<AgentSummary> updateAgent({
    required String agentId,
    required String name,
    required String description,
    required String runtimeAgent,
    required String model,
    String? workspacePath,
  });

  /// Update a project's name.
  Future<void> updateProject({required UpdateProjectRequest req});

  /// Enable or disable one host-side skill.
  Future<WriteHostSkillConfigResponse> writeHostSkillConfig({
    String? hostDeviceId,
    required String path,
    required bool enabled,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionState>>
abstract class SessionState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionSummary>>
abstract class SessionSummary implements RustOpaqueInterface {
  AgentName get agent;

  SessionEndReason? get endReason;

  PlatformInt64? get endedAtMs;

  PlatformInt64 get firstTsMs;

  PlatformInt64 get lastTsMs;

  int get messageCount;

  bool get needsContinue;

  String? get parentSessionId;

  String get sessionId;

  SessionState get state;

  String? get title;

  set agent(AgentName agent);

  set endReason(SessionEndReason? endReason);

  set endedAtMs(PlatformInt64? endedAtMs);

  set firstTsMs(PlatformInt64 firstTsMs);

  set lastTsMs(PlatformInt64 lastTsMs);

  set messageCount(int messageCount);

  set needsContinue(bool needsContinue);

  set parentSessionId(String? parentSessionId);

  set sessionId(String sessionId);

  set state(SessionState state);

  set title(String? title);
}

class AgentDescriptor {
  final AgentName name;
  final String displayName;
  final String? path;
  final String? version;
  final AgentStatus status;
  final bool supportsModelSelection;
  final bool supportsReasoningEffort;

  const AgentDescriptor({
    required this.name,
    required this.displayName,
    this.path,
    this.version,
    required this.status,
    required this.supportsModelSelection,
    required this.supportsReasoningEffort,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      path.hashCode ^
      version.hashCode ^
      status.hashCode ^
      supportsModelSelection.hashCode ^
      supportsReasoningEffort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentDescriptor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          path == other.path &&
          version == other.version &&
          status == other.status &&
          supportsModelSelection == other.supportsModelSelection &&
          supportsReasoningEffort == other.supportsReasoningEffort;
}

enum AgentName { codex, claude, gemini, opencode, grok }

class AgentSessionSummaryDto {
  final String sessionId;
  final String conversationId;
  final String? agentId;
  final AgentName? agent;
  final String status;
  final PlatformInt64 startedAtMs;
  final PlatformInt64? endedAtMs;
  final String? title;
  final PlatformInt64 lastActivityAtMs;
  final int messageCount;
  final SessionEndReason? endReason;

  const AgentSessionSummaryDto({
    required this.sessionId,
    required this.conversationId,
    this.agentId,
    this.agent,
    required this.status,
    required this.startedAtMs,
    this.endedAtMs,
    this.title,
    required this.lastActivityAtMs,
    required this.messageCount,
    this.endReason,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      conversationId.hashCode ^
      agentId.hashCode ^
      agent.hashCode ^
      status.hashCode ^
      startedAtMs.hashCode ^
      endedAtMs.hashCode ^
      title.hashCode ^
      lastActivityAtMs.hashCode ^
      messageCount.hashCode ^
      endReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentSessionSummaryDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          conversationId == other.conversationId &&
          agentId == other.agentId &&
          agent == other.agent &&
          status == other.status &&
          startedAtMs == other.startedAtMs &&
          endedAtMs == other.endedAtMs &&
          title == other.title &&
          lastActivityAtMs == other.lastActivityAtMs &&
          messageCount == other.messageCount &&
          endReason == other.endReason;
}

@freezed
sealed class AgentStatus with _$AgentStatus {
  const AgentStatus._();

  const factory AgentStatus.ok() = AgentStatus_Ok;
  const factory AgentStatus.missing() = AgentStatus_Missing;
  const factory AgentStatus.error({required String reason}) = AgentStatus_Error;
}

class AgentSummary {
  final String agentId;
  final String ownerAccountId;
  final String name;
  final String description;
  final String runtimeAgent;
  final String model;
  final String? workspacePath;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const AgentSummary({
    required this.agentId,
    required this.ownerAccountId,
    required this.name,
    required this.description,
    required this.runtimeAgent,
    required this.model,
    this.workspacePath,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      agentId.hashCode ^
      ownerAccountId.hashCode ^
      name.hashCode ^
      description.hashCode ^
      runtimeAgent.hashCode ^
      model.hashCode ^
      workspacePath.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentSummary &&
          runtimeType == other.runtimeType &&
          agentId == other.agentId &&
          ownerAccountId == other.ownerAccountId &&
          name == other.name &&
          description == other.description &&
          runtimeAgent == other.runtimeAgent &&
          model == other.model &&
          workspacePath == other.workspacePath &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

class ArtifactRef {
  final String sessionId;
  final String artifactId;
  final BigInt sizeBytes;
  final String sha256;
  final String mediaType;

  const ArtifactRef({
    required this.sessionId,
    required this.artifactId,
    required this.sizeBytes,
    required this.sha256,
    required this.mediaType,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      artifactId.hashCode ^
      sizeBytes.hashCode ^
      sha256.hashCode ^
      mediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtifactRef &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          artifactId == other.artifactId &&
          sizeBytes == other.sizeBytes &&
          sha256 == other.sha256 &&
          mediaType == other.mediaType;
}

@freezed
sealed class AuthStateFrame with _$AuthStateFrame {
  const AuthStateFrame._();

  const factory AuthStateFrame.unauthenticated() =
      AuthStateFrame_Unauthenticated;
  const factory AuthStateFrame.authenticated({required AuthSummary account}) =
      AuthStateFrame_Authenticated;
  const factory AuthStateFrame.refreshing() = AuthStateFrame_Refreshing;
  const factory AuthStateFrame.refreshFailed({required MinosError error}) =
      AuthStateFrame_RefreshFailed;
}

class AuthSummary {
  final String accountId;
  final String email;

  const AuthSummary({required this.accountId, required this.email});

  @override
  int get hashCode => accountId.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthSummary &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email;
}

class ChatMessageReplySummary {
  final String messageId;
  final UserSummary sender;
  final String text;
  final PlatformInt64? recalledAtMs;

  const ChatMessageReplySummary({
    required this.messageId,
    required this.sender,
    required this.text,
    this.recalledAtMs,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      sender.hashCode ^
      text.hashCode ^
      recalledAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageReplySummary &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          sender == other.sender &&
          text == other.text &&
          recalledAtMs == other.recalledAtMs;
}

class ChatMessageSummary {
  final String messageId;
  final String conversationId;
  final UserSummary sender;
  final String text;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 messageSeq;
  final ChatMessageReplySummary? replyTo;
  final PlatformInt64? recalledAtMs;
  final List<String> mentionedAccountIds;
  final SenderType senderType;
  final List<ReactionGroup> reactions;

  const ChatMessageSummary({
    required this.messageId,
    required this.conversationId,
    required this.sender,
    required this.text,
    required this.createdAtMs,
    required this.messageSeq,
    this.replyTo,
    this.recalledAtMs,
    required this.mentionedAccountIds,
    required this.senderType,
    required this.reactions,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      conversationId.hashCode ^
      sender.hashCode ^
      text.hashCode ^
      createdAtMs.hashCode ^
      messageSeq.hashCode ^
      replyTo.hashCode ^
      recalledAtMs.hashCode ^
      mentionedAccountIds.hashCode ^
      senderType.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageSummary &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          conversationId == other.conversationId &&
          sender == other.sender &&
          text == other.text &&
          createdAtMs == other.createdAtMs &&
          messageSeq == other.messageSeq &&
          replyTo == other.replyTo &&
          recalledAtMs == other.recalledAtMs &&
          mentionedAccountIds == other.mentionedAccountIds &&
          senderType == other.senderType &&
          reactions == other.reactions;
}

@freezed
sealed class ConnectionState with _$ConnectionState {
  const ConnectionState._();

  const factory ConnectionState.disconnected() = ConnectionState_Disconnected;
  const factory ConnectionState.pairing() = ConnectionState_Pairing;
  const factory ConnectionState.connected() = ConnectionState_Connected;
  const factory ConnectionState.reconnecting({required int attempt}) =
      ConnectionState_Reconnecting;
}

class ConversationAgentMembersResponse {
  final List<AgentSummary> agents;

  const ConversationAgentMembersResponse({required this.agents});

  @override
  int get hashCode => agents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationAgentMembersResponse &&
          runtimeType == other.runtimeType &&
          agents == other.agents;
}

enum ConversationKind { direct, group }

class ConversationMembersResponse {
  final List<UserSummary> members;

  const ConversationMembersResponse({required this.members});

  @override
  int get hashCode => members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationMembersResponse &&
          runtimeType == other.runtimeType &&
          members == other.members;
}

class ConversationReadResponse {
  final PlatformInt64? lastReadSeq;
  final PlatformInt64? lastReadAtMs;

  const ConversationReadResponse({this.lastReadSeq, this.lastReadAtMs});

  @override
  int get hashCode => lastReadSeq.hashCode ^ lastReadAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationReadResponse &&
          runtimeType == other.runtimeType &&
          lastReadSeq == other.lastReadSeq &&
          lastReadAtMs == other.lastReadAtMs;
}

class ConversationResponse {
  final String conversationId;

  const ConversationResponse({required this.conversationId});

  @override
  int get hashCode => conversationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationResponse &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId;
}

class ConversationSummary {
  final String conversationId;
  final ConversationKind kind;
  final String title;
  final UserSummary? counterpart;
  final int memberCount;
  final String? lastMessagePreview;
  final PlatformInt64 lastMessageAtMs;
  final int unreadCount;
  final int unreadMentionCount;

  const ConversationSummary({
    required this.conversationId,
    required this.kind,
    required this.title,
    this.counterpart,
    required this.memberCount,
    this.lastMessagePreview,
    required this.lastMessageAtMs,
    required this.unreadCount,
    required this.unreadMentionCount,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      counterpart.hashCode ^
      memberCount.hashCode ^
      lastMessagePreview.hashCode ^
      lastMessageAtMs.hashCode ^
      unreadCount.hashCode ^
      unreadMentionCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationSummary &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          kind == other.kind &&
          title == other.title &&
          counterpart == other.counterpart &&
          memberCount == other.memberCount &&
          lastMessagePreview == other.lastMessagePreview &&
          lastMessageAtMs == other.lastMessageAtMs &&
          unreadCount == other.unreadCount &&
          unreadMentionCount == other.unreadMentionCount;
}

class ConversationsResponse {
  final List<ConversationSummary> conversations;

  const ConversationsResponse({required this.conversations});

  @override
  int get hashCode => conversations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationsResponse &&
          runtimeType == other.runtimeType &&
          conversations == other.conversations;
}

class CreateProjectRequest {
  final String name;
  final String workspaceSlug;
  final String? workspacePath;

  const CreateProjectRequest({
    required this.name,
    required this.workspaceSlug,
    this.workspacePath,
  });

  @override
  int get hashCode =>
      name.hashCode ^ workspaceSlug.hashCode ^ workspacePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateProjectRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          workspaceSlug == other.workspaceSlug &&
          workspacePath == other.workspacePath;
}

class CreateProjectResponse {
  final ProjectSummary project;

  const CreateProjectResponse({required this.project});

  @override
  int get hashCode => project.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateProjectResponse &&
          runtimeType == other.runtimeType &&
          project == other.project;
}

class DeleteProjectRequest {
  final String projectId;

  const DeleteProjectRequest({required this.projectId});

  @override
  int get hashCode => projectId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteProjectRequest &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId;
}

@freezed
sealed class DisplayPayload with _$DisplayPayload {
  const DisplayPayload._();

  const factory DisplayPayload.inline({required String text}) =
      DisplayPayload_Inline;
  const factory DisplayPayload.streamingWindow({
    required String head,
    required BigInt receivedBytes,
    ArtifactRef? artifact,
  }) = DisplayPayload_StreamingWindow;
  const factory DisplayPayload.windowedFinal({
    required String head,
    required String tail,
    required BigInt omittedBytes,
    required ArtifactRef artifact,
  }) = DisplayPayload_WindowedFinal;
}

enum ErrorKind {
  bindFailed,
  connectFailed,
  disconnected,
  pairingTokenInvalid,
  pairingStateMismatch,
  deviceNotTrusted,
  storeIo,
  storeCorrupt,
  cliProbeTimeout,
  cliProbeFailed,
  rpcCallFailed,
  unauthorized,
  connectionStateMismatch,
  envelopeVersionUnsupported,
  peerOffline,
  backendInternal,
  codexSpawnFailed,
  codexConnectFailed,
  codexProtocolError,
  geminiSpawnFailed,
  acpProtocolError,
  agentAlreadyRunning,
  agentNotRunning,
  agentNotSupported,
  agentSessionIdMismatch,
  ingestSeqConflict,
  sessionNotFound,
  translationNotImplemented,
  translationFailed,
  pairingQrVersionUnsupported,
  timeout,
  notConnected,
  requestDropped,
  authRefreshFailed,
  emailTaken,
  weakPassword,
  rateLimited,
  invalidCredentials,
  agentStartFailed,
  pairingTokenExpired,
}

enum FriendRequestStatus { pending, accepted, rejected, canceled }

class FriendRequestSummary {
  final String requestId;
  final UserSummary from;
  final UserSummary to;
  final FriendRequestStatus status;
  final PlatformInt64 createdAtMs;
  final PlatformInt64? resolvedAtMs;

  const FriendRequestSummary({
    required this.requestId,
    required this.from,
    required this.to,
    required this.status,
    required this.createdAtMs,
    this.resolvedAtMs,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      from.hashCode ^
      to.hashCode ^
      status.hashCode ^
      createdAtMs.hashCode ^
      resolvedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendRequestSummary &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          from == other.from &&
          to == other.to &&
          status == other.status &&
          createdAtMs == other.createdAtMs &&
          resolvedAtMs == other.resolvedAtMs;
}

class FriendRequestsResponse {
  final List<FriendRequestSummary> incoming;
  final List<FriendRequestSummary> outgoing;

  const FriendRequestsResponse({
    required this.incoming,
    required this.outgoing,
  });

  @override
  int get hashCode => incoming.hashCode ^ outgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendRequestsResponse &&
          runtimeType == other.runtimeType &&
          incoming == other.incoming &&
          outgoing == other.outgoing;
}

class FriendSummary {
  final String accountId;
  final String minosId;
  final String displayName;
  final PlatformInt64 createdAtMs;

  const FriendSummary({
    required this.accountId,
    required this.minosId,
    required this.displayName,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      minosId.hashCode ^
      displayName.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendSummary &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          minosId == other.minosId &&
          displayName == other.displayName &&
          createdAtMs == other.createdAtMs;
}

class FriendsResponse {
  final List<FriendSummary> friends;

  const FriendsResponse({required this.friends});

  @override
  int get hashCode => friends.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendsResponse &&
          runtimeType == other.runtimeType &&
          friends == other.friends;
}

class HostSkillError {
  final String path;
  final String message;

  const HostSkillError({required this.path, required this.message});

  @override
  int get hashCode => path.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostSkillError &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          message == other.message;
}

class HostSkillSummary {
  final String name;
  final String path;
  final String description;
  final bool enabled;
  final String scope;
  final String? displayName;
  final String? shortDescription;

  const HostSkillSummary({
    required this.name,
    required this.path,
    required this.description,
    required this.enabled,
    required this.scope,
    this.displayName,
    this.shortDescription,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      description.hashCode ^
      enabled.hashCode ^
      scope.hashCode ^
      displayName.hashCode ^
      shortDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostSkillSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          description == other.description &&
          enabled == other.enabled &&
          scope == other.scope &&
          displayName == other.displayName &&
          shortDescription == other.shortDescription;
}

class HostSkillsEntry {
  final String cwd;
  final List<HostSkillError> errors;
  final List<HostSkillSummary> skills;

  const HostSkillsEntry({
    required this.cwd,
    required this.errors,
    required this.skills,
  });

  @override
  int get hashCode => cwd.hashCode ^ errors.hashCode ^ skills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostSkillsEntry &&
          runtimeType == other.runtimeType &&
          cwd == other.cwd &&
          errors == other.errors &&
          skills == other.skills;
}

/// Dart-visible mirror of `minos_protocol::HostSummary`. One row returned by
/// `GET /v1/hosts`.
class HostSummaryDto {
  final String hostDeviceId;
  final String hostDisplayName;
  final PlatformInt64 pairedAtMs;
  final String pairedViaDeviceId;
  final bool online;

  const HostSummaryDto({
    required this.hostDeviceId,
    required this.hostDisplayName,
    required this.pairedAtMs,
    required this.pairedViaDeviceId,
    required this.online,
  });

  @override
  int get hashCode =>
      hostDeviceId.hashCode ^
      hostDisplayName.hashCode ^
      pairedAtMs.hashCode ^
      pairedViaDeviceId.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostSummaryDto &&
          runtimeType == other.runtimeType &&
          hostDeviceId == other.hostDeviceId &&
          hostDisplayName == other.hostDisplayName &&
          pairedAtMs == other.pairedAtMs &&
          pairedViaDeviceId == other.pairedViaDeviceId &&
          online == other.online;
}

class HostWorkspaceSummary {
  final String path;
  final String displayName;
  final bool isGitRepo;

  const HostWorkspaceSummary({
    required this.path,
    required this.displayName,
    required this.isGitRepo,
  });

  @override
  int get hashCode => path.hashCode ^ displayName.hashCode ^ isGitRepo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostWorkspaceSummary &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          displayName == other.displayName &&
          isGitRepo == other.isGitRepo;
}

enum Lang { zh, en }

class ListAgentsResponse {
  final List<AgentSummary> agents;

  const ListAgentsResponse({required this.agents});

  @override
  int get hashCode => agents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListAgentsResponse &&
          runtimeType == other.runtimeType &&
          agents == other.agents;
}

class ListChatMessagesResponse {
  final List<ChatMessageSummary> messages;
  final PlatformInt64? nextBeforeSeq;

  const ListChatMessagesResponse({required this.messages, this.nextBeforeSeq});

  @override
  int get hashCode => messages.hashCode ^ nextBeforeSeq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListChatMessagesResponse &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          nextBeforeSeq == other.nextBeforeSeq;
}

class ListHostSkillsResponse {
  final List<HostSkillsEntry> data;

  const ListHostSkillsResponse({required this.data});

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListHostSkillsResponse &&
          runtimeType == other.runtimeType &&
          data == other.data;
}

class ListHostWorkspacesResponse {
  final String root;
  final List<HostWorkspaceSummary> workspaces;

  const ListHostWorkspacesResponse({
    required this.root,
    required this.workspaces,
  });

  @override
  int get hashCode => root.hashCode ^ workspaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListHostWorkspacesResponse &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          workspaces == other.workspaces;
}

class ListProjectSessionsParams {
  final String projectId;
  final int limit;
  final PlatformInt64? beforeTsMs;

  const ListProjectSessionsParams({
    required this.projectId,
    required this.limit,
    this.beforeTsMs,
  });

  @override
  int get hashCode => projectId.hashCode ^ limit.hashCode ^ beforeTsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListProjectSessionsParams &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          limit == other.limit &&
          beforeTsMs == other.beforeTsMs;
}

class ListProjectSessionsResponse {
  final List<SessionSummary> sessions;

  const ListProjectSessionsResponse({required this.sessions});

  @override
  int get hashCode => sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListProjectSessionsResponse &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions;
}

class ListProjectsResponse {
  final List<ProjectSummary> projects;

  const ListProjectsResponse({required this.projects});

  @override
  int get hashCode => projects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListProjectsResponse &&
          runtimeType == other.runtimeType &&
          projects == other.projects;
}

class ListSessionsParams {
  final int limit;
  final PlatformInt64? beforeTsMs;
  final AgentName? agent;

  const ListSessionsParams({required this.limit, this.beforeTsMs, this.agent});

  @override
  int get hashCode => limit.hashCode ^ beforeTsMs.hashCode ^ agent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListSessionsParams &&
          runtimeType == other.runtimeType &&
          limit == other.limit &&
          beforeTsMs == other.beforeTsMs &&
          agent == other.agent;
}

class ListSessionsResponse {
  final List<SessionSummary> sessions;
  final PlatformInt64? nextBeforeTsMs;

  const ListSessionsResponse({required this.sessions, this.nextBeforeTsMs});

  @override
  int get hashCode => sessions.hashCode ^ nextBeforeTsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListSessionsResponse &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions &&
          nextBeforeTsMs == other.nextBeforeTsMs;
}

/// Severity tag mirrored from `minos_mobile::log_capture::LogLevel`.
enum LogLevel { trace, debug, info, warn, error }

/// Single tracing event captured by the in-process ring buffer.
class LogRecord {
  final LogLevel level;
  final String target;
  final String message;
  final PlatformInt64 tsMs;

  const LogRecord({
    required this.level,
    required this.target,
    required this.message,
    required this.tsMs,
  });

  @override
  int get hashCode =>
      level.hashCode ^ target.hashCode ^ message.hashCode ^ tsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogRecord &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          target == other.target &&
          message == other.message &&
          tsMs == other.tsMs;
}

enum MessageRole { user, assistant, system }

@freezed
sealed class MinosError with _$MinosError implements FrbException {
  const MinosError._();

  const factory MinosError.bindFailed({
    required String addr,
    required String message,
  }) = MinosError_BindFailed;
  const factory MinosError.connectFailed({
    required String url,
    required String message,
  }) = MinosError_ConnectFailed;
  const factory MinosError.disconnected({required String reason}) =
      MinosError_Disconnected;
  const factory MinosError.pairingTokenInvalid() =
      MinosError_PairingTokenInvalid;
  const factory MinosError.pairingStateMismatch({
    required PairingState actual,
  }) = MinosError_PairingStateMismatch;
  const factory MinosError.deviceNotTrusted({required String deviceId}) =
      MinosError_DeviceNotTrusted;
  const factory MinosError.storeIo({
    required String path,
    required String message,
  }) = MinosError_StoreIo;
  const factory MinosError.storeCorrupt({
    required String path,
    required String message,
  }) = MinosError_StoreCorrupt;
  const factory MinosError.cliProbeTimeout({
    required String bin,
    required BigInt timeoutMs,
  }) = MinosError_CliProbeTimeout;
  const factory MinosError.cliProbeFailed({
    required String bin,
    required String message,
  }) = MinosError_CliProbeFailed;
  const factory MinosError.rpcCallFailed({
    required String method,
    required String message,
  }) = MinosError_RpcCallFailed;
  const factory MinosError.unauthorized({required String reason}) =
      MinosError_Unauthorized;
  const factory MinosError.connectionStateMismatch({
    required String expected,
    required String actual,
  }) = MinosError_ConnectionStateMismatch;
  const factory MinosError.envelopeVersionUnsupported({required int version}) =
      MinosError_EnvelopeVersionUnsupported;
  const factory MinosError.peerOffline({required String peerDeviceId}) =
      MinosError_PeerOffline;
  const factory MinosError.backendInternal({required String message}) =
      MinosError_BackendInternal;
  const factory MinosError.codexSpawnFailed({required String message}) =
      MinosError_CodexSpawnFailed;
  const factory MinosError.codexConnectFailed({
    required String url,
    required String message,
  }) = MinosError_CodexConnectFailed;
  const factory MinosError.codexProtocolError({
    required String method,
    required String message,
  }) = MinosError_CodexProtocolError;
  const factory MinosError.geminiSpawnFailed({required String message}) =
      MinosError_GeminiSpawnFailed;
  const factory MinosError.acpProtocolError({
    required String method,
    required String message,
  }) = MinosError_AcpProtocolError;
  const factory MinosError.agentAlreadyRunning() =
      MinosError_AgentAlreadyRunning;
  const factory MinosError.agentNotRunning() = MinosError_AgentNotRunning;
  const factory MinosError.agentNotSupported({required AgentName agent}) =
      MinosError_AgentNotSupported;
  const factory MinosError.agentSessionIdMismatch() =
      MinosError_AgentSessionIdMismatch;
  const factory MinosError.ingestSeqConflict({
    required String sessionId,
    required BigInt seq,
  }) = MinosError_IngestSeqConflict;
  const factory MinosError.sessionNotFound({required String sessionId}) =
      MinosError_SessionNotFound;
  const factory MinosError.translationNotImplemented({
    required AgentName agent,
  }) = MinosError_TranslationNotImplemented;
  const factory MinosError.translationFailed({
    required AgentName agent,
    required String message,
  }) = MinosError_TranslationFailed;
  const factory MinosError.pairingQrVersionUnsupported({required int version}) =
      MinosError_PairingQrVersionUnsupported;
  const factory MinosError.timeout() = MinosError_Timeout;
  const factory MinosError.notConnected() = MinosError_NotConnected;
  const factory MinosError.requestDropped() = MinosError_RequestDropped;
  const factory MinosError.authRefreshFailed({required String message}) =
      MinosError_AuthRefreshFailed;
  const factory MinosError.emailTaken() = MinosError_EmailTaken;
  const factory MinosError.weakPassword() = MinosError_WeakPassword;
  const factory MinosError.rateLimited({required int retryAfterS}) =
      MinosError_RateLimited;
  const factory MinosError.invalidCredentials() = MinosError_InvalidCredentials;
  const factory MinosError.agentStartFailed({required String reason}) =
      MinosError_AgentStartFailed;
  const factory MinosError.pairingTokenExpired() =
      MinosError_PairingTokenExpired;
}

class MyProfileResponse {
  final String accountId;
  final String email;
  final String minosId;
  final String? displayName;

  const MyProfileResponse({
    required this.accountId,
    required this.email,
    required this.minosId,
    this.displayName,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      email.hashCode ^
      minosId.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MyProfileResponse &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email &&
          minosId == other.minosId &&
          displayName == other.displayName;
}

enum PairingState { unpaired, awaitingPeer, paired }

/// Durable mobile pairing snapshot mirrored into the iOS keychain.
///
/// Phase 4 added the five auth fields (access/refresh tokens + bound
/// account identity) so the Dart-side secure store can rehydrate the full
/// session on cold launch. All five auth fields are persisted as a tuple —
/// either every one is present or all are `None`.
///
/// ADR-0020 dropped the device_secret from this snapshot — the iOS rail
/// is bearer-only.
///
/// Backend URL and CF Access service-token headers were dropped from the
/// snapshot when pairing transitioned to compile-time `build_config` — the
/// transport-edge values never round-trip through durable storage now.
class PersistedPairingState {
  final String? deviceId;
  final String? accessToken;
  final PlatformInt64? accessExpiresAtMs;
  final String? refreshToken;
  final String? accountId;
  final String? accountEmail;

  const PersistedPairingState({
    this.deviceId,
    this.accessToken,
    this.accessExpiresAtMs,
    this.refreshToken,
    this.accountId,
    this.accountEmail,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      accessToken.hashCode ^
      accessExpiresAtMs.hashCode ^
      refreshToken.hashCode ^
      accountId.hashCode ^
      accountEmail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersistedPairingState &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          accessExpiresAtMs == other.accessExpiresAtMs &&
          refreshToken == other.refreshToken &&
          accountId == other.accountId &&
          accountEmail == other.accountEmail;
}

class ProjectSummary {
  final String projectId;
  final String name;
  final String workspaceSlug;
  final String? workspacePath;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;
  final int threadCount;

  const ProjectSummary({
    required this.projectId,
    required this.name,
    required this.workspaceSlug,
    this.workspacePath,
    required this.createdAtMs,
    required this.updatedAtMs,
    required this.threadCount,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      name.hashCode ^
      workspaceSlug.hashCode ^
      workspacePath.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      threadCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSummary &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          name == other.name &&
          workspaceSlug == other.workspaceSlug &&
          workspacePath == other.workspacePath &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          threadCount == other.threadCount;
}

class ReactionActor {
  final String actorId;
  final String actorKind;
  final String displayName;

  const ReactionActor({
    required this.actorId,
    required this.actorKind,
    required this.displayName,
  });

  @override
  int get hashCode =>
      actorId.hashCode ^ actorKind.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionActor &&
          runtimeType == other.runtimeType &&
          actorId == other.actorId &&
          actorKind == other.actorKind &&
          displayName == other.displayName;
}

class ReactionGroup {
  final String emoji;
  final int count;
  final bool reactedByMe;
  final List<ReactionActor> actors;

  const ReactionGroup({
    required this.emoji,
    required this.count,
    required this.reactedByMe,
    required this.actors,
  });

  @override
  int get hashCode =>
      emoji.hashCode ^ count.hashCode ^ reactedByMe.hashCode ^ actors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionGroup &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          count == other.count &&
          reactedByMe == other.reactedByMe &&
          actors == other.actors;
}

class ReadSessionParams {
  final String sessionId;
  final BigInt? fromSeq;
  final int limit;

  const ReadSessionParams({
    required this.sessionId,
    this.fromSeq,
    required this.limit,
  });

  @override
  int get hashCode => sessionId.hashCode ^ fromSeq.hashCode ^ limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadSessionParams &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          fromSeq == other.fromSeq &&
          limit == other.limit;
}

class ReadSessionResponse {
  final List<UiEventMessage> uiEvents;
  final BigInt? nextSeq;
  final SessionEndReason? sessionEndReason;

  const ReadSessionResponse({
    required this.uiEvents,
    this.nextSeq,
    this.sessionEndReason,
  });

  @override
  int get hashCode =>
      uiEvents.hashCode ^ nextSeq.hashCode ^ sessionEndReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadSessionResponse &&
          runtimeType == other.runtimeType &&
          uiEvents == other.uiEvents &&
          nextSeq == other.nextSeq &&
          sessionEndReason == other.sessionEndReason;
}

class RequestTraceRecord {
  final BigInt id;
  final RequestTraceTransport transport;
  final String method;
  final String target;
  final String? sessionId;
  final String? requestSummary;
  final String? responseSummary;
  final String? errorDetail;
  final RequestTraceStatus status;
  final int? statusCode;
  final PlatformInt64 startedAtMs;
  final PlatformInt64? completedAtMs;
  final int? durationMs;

  const RequestTraceRecord({
    required this.id,
    required this.transport,
    required this.method,
    required this.target,
    this.sessionId,
    this.requestSummary,
    this.responseSummary,
    this.errorDetail,
    required this.status,
    this.statusCode,
    required this.startedAtMs,
    this.completedAtMs,
    this.durationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      transport.hashCode ^
      method.hashCode ^
      target.hashCode ^
      sessionId.hashCode ^
      requestSummary.hashCode ^
      responseSummary.hashCode ^
      errorDetail.hashCode ^
      status.hashCode ^
      statusCode.hashCode ^
      startedAtMs.hashCode ^
      completedAtMs.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestTraceRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          transport == other.transport &&
          method == other.method &&
          target == other.target &&
          sessionId == other.sessionId &&
          requestSummary == other.requestSummary &&
          responseSummary == other.responseSummary &&
          errorDetail == other.errorDetail &&
          status == other.status &&
          statusCode == other.statusCode &&
          startedAtMs == other.startedAtMs &&
          completedAtMs == other.completedAtMs &&
          durationMs == other.durationMs;
}

enum RequestTraceStatus { pending, success, failure }

enum RequestTraceTransport { http, rpc }

enum SenderType { user, agent }

@freezed
sealed class SessionEndReason with _$SessionEndReason {
  const SessionEndReason._();

  const factory SessionEndReason.userStopped() = SessionEndReason_UserStopped;
  const factory SessionEndReason.agentDone() = SessionEndReason_AgentDone;
  const factory SessionEndReason.crashed({required String message}) =
      SessionEndReason_Crashed;
  const factory SessionEndReason.timeout() = SessionEndReason_Timeout;
  const factory SessionEndReason.hostDisconnected() =
      SessionEndReason_HostDisconnected;
}

/// Dart-visible shape of `minos_mobile::SocialEventFrame`.
class SocialEventFrame {
  final String conversationId;

  /// `"message"` | `"reaction_updated"`.
  final String kind;
  final ChatMessageSummary message;

  const SocialEventFrame({
    required this.conversationId,
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^ kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SocialEventFrame &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          kind == other.kind &&
          message == other.message;
}

enum SubagentStatus { running, completed, failed, interrupted }

class ToggleReactionResponse {
  final String messageId;
  final String conversationId;
  final List<ReactionGroup> reactions;
  final String action;

  const ToggleReactionResponse({
    required this.messageId,
    required this.conversationId,
    required this.reactions,
    required this.action,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      conversationId.hashCode ^
      reactions.hashCode ^
      action.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToggleReactionResponse &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          conversationId == other.conversationId &&
          reactions == other.reactions &&
          action == other.action;
}

/// Dart-visible shape of `minos_mobile::UiEventFrame`. Held as a separate
/// type (rather than mirrored) so the `ui` field lands as the mirrored
/// `UiEventMessage` variant on the Dart side.
class UiEventFrame {
  final String sessionId;
  final BigInt seq;
  final UiEventMessage ui;
  final PlatformInt64 tsMs;

  const UiEventFrame({
    required this.sessionId,
    required this.seq,
    required this.ui,
    required this.tsMs,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ seq.hashCode ^ ui.hashCode ^ tsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEventFrame &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          seq == other.seq &&
          ui == other.ui &&
          tsMs == other.tsMs;
}

@freezed
sealed class UiEventMessage with _$UiEventMessage {
  const UiEventMessage._();

  const factory UiEventMessage.sessionOpened({
    required String sessionId,
    required AgentName agent,
    String? title,
    required PlatformInt64 openedAtMs,
  }) = UiEventMessage_SessionOpened;
  const factory UiEventMessage.sessionTitleUpdated({
    required String sessionId,
    required String title,
  }) = UiEventMessage_SessionTitleUpdated;
  const factory UiEventMessage.sessionClosed({
    required String sessionId,
    required SessionEndReason reason,
    required PlatformInt64 closedAtMs,
  }) = UiEventMessage_SessionClosed;
  const factory UiEventMessage.messageStarted({
    required String messageId,
    required MessageRole role,
    required PlatformInt64 startedAtMs,
  }) = UiEventMessage_MessageStarted;
  const factory UiEventMessage.messageCompleted({
    required String messageId,
    required PlatformInt64 finishedAtMs,
  }) = UiEventMessage_MessageCompleted;
  const factory UiEventMessage.textDelta({
    required String messageId,
    required DisplayPayload text,
  }) = UiEventMessage_TextDelta;
  const factory UiEventMessage.textReplace({
    required String messageId,
    required DisplayPayload text,
  }) = UiEventMessage_TextReplace;
  const factory UiEventMessage.reasoningDelta({
    required String messageId,
    required DisplayPayload text,
  }) = UiEventMessage_ReasoningDelta;
  const factory UiEventMessage.reasoningReplace({
    required String messageId,
    required DisplayPayload text,
  }) = UiEventMessage_ReasoningReplace;
  const factory UiEventMessage.toolCallPlaced({
    required String messageId,
    required String toolCallId,
    required String name,
    required DisplayPayload argsJson,
  }) = UiEventMessage_ToolCallPlaced;
  const factory UiEventMessage.toolCallCompleted({
    required String toolCallId,
    required DisplayPayload output,
    required bool isError,
  }) = UiEventMessage_ToolCallCompleted;
  const factory UiEventMessage.subagentSpawned({
    required String parentSessionId,
    required String subSessionId,
    required String toolCallId,
    required AgentName agent,
    String? model,
    String? prompt,
    String? title,
  }) = UiEventMessage_SubagentSpawned;
  const factory UiEventMessage.subagentStatusUpdated({
    required String subSessionId,
    required SubagentStatus status,
  }) = UiEventMessage_SubagentStatusUpdated;
  const factory UiEventMessage.error({
    required String code,
    required String message,
    String? messageId,
  }) = UiEventMessage_Error;
  const factory UiEventMessage.raw({
    required String kind,
    required String payloadJson,
  }) = UiEventMessage_Raw;
}

class UpdateProjectRequest {
  final String projectId;
  final String name;

  const UpdateProjectRequest({required this.projectId, required this.name});

  @override
  int get hashCode => projectId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateProjectRequest &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          name == other.name;
}

class UserSummary {
  final String accountId;
  final String minosId;
  final String displayName;

  const UserSummary({
    required this.accountId,
    required this.minosId,
    required this.displayName,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^ minosId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserSummary &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          minosId == other.minosId &&
          displayName == other.displayName;
}

class WriteHostSkillConfigResponse {
  final bool effectiveEnabled;

  const WriteHostSkillConfigResponse({required this.effectiveEnabled});

  @override
  int get hashCode => effectiveEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WriteHostSkillConfigResponse &&
          runtimeType == other.runtimeType &&
          effectiveEnabled == other.effectiveEnabled;
}
