// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'minos.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `frb_runtime`, `parse_device_id`, `spawn_state_forwarder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initialize mobile-side Rust logging with the given directory (supplied by
/// Dart, typically `<Documents>/Minos/Logs`). Idempotent — safe to call once
/// per launch.
Future<void> initLogging({required String logDir}) =>
    RustLib.instance.api.crateApiMinosInitLogging(logDir: logDir);

/// Localize an `ErrorKind` into user-facing copy. Mirrors the UniFFI adapter's
/// `kind_message` so Dart can render localized error strings without hard-
/// coding them.
String kindMessage({required ErrorKind kind, required Lang lang}) =>
    RustLib.instance.api.crateApiMinosKindMessage(kind: kind, lang: lang);

/// Snapshot the records currently held in the ring buffer (oldest first).
/// Pair this with [`subscribe_log_records`] when populating a freshly
/// mounted log panel so prior events are not lost.
List<LogRecord> recentLogRecords() =>
    RustLib.instance.api.crateApiMinosRecentLogRecords();

/// Subscribe to the live tail. Each subscriber gets its own broadcast
/// receiver; lagging subscribers drop old records (the producer is never
/// blocked). The spawned task exits when the Dart side drops the stream.
Stream<LogRecord> subscribeLogRecords() =>
    RustLib.instance.api.crateApiMinosSubscribeLogRecords();

List<RequestTraceRecord> recentRequestTraces() =>
    RustLib.instance.api.crateApiMinosRecentRequestTraces();

void clearRequestTraces() =>
    RustLib.instance.api.crateApiMinosClearRequestTraces();

Stream<RequestTraceRecord> subscribeRequestTraces() =>
    RustLib.instance.api.crateApiMinosSubscribeRequestTraces();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>
abstract class MobileClient implements RustOpaqueInterface {
  /// Read the current active Mac id, or `None` if no pair has been
  /// completed yet.
  Future<String?> activeHost();

  /// Permanently close the given thread. Idempotent.
  Future<void> closeThread({required String threadId});

  /// Current connection state, read from the watch-channel cache. Cheap and
  /// synchronous.
  ConnectionState currentState();

  /// Forget a specific paired Mac. The path-bound `host_device_id` is
  /// the Mac to forget. Idempotent. ADR-0020 supersedes the old
  /// `forget_peer` (single-peer) call.
  Future<void> forgetHost({required String hostDeviceId});

  /// Pause an in-flight turn on the given thread. Best-effort. The thread
  /// transitions to `Suspended { UserInterrupt }` regardless of whether the
  /// codex side acknowledges in time.
  Future<void> interruptThread({required String threadId});

  /// Detect the CLI agents available on the paired runtime.
  Future<List<AgentDescriptor>> listClis();

  /// List every Mac paired to the caller's account.
  Future<List<HostSummaryDto>> listPairedHosts();

  /// Request a page of thread summaries.
  Future<ListThreadsResponse> listThreads({required ListThreadsParams req});

  /// Log into an existing account on the backend. Same shape as
  /// `register` modulo the create-vs-find behaviour on the server.
  Future<AuthSummary> login({required String email, required String password});

  /// Log out of the current session. Best-effort `stop_agent`, then
  /// revoke the refresh token server-side, then wipe local state.
  Future<void> logout();

  /// Construct a client backed by the built-in in-memory pairing store.
  /// Synchronous — no I/O happens until a pairing method is called.
  factory MobileClient({required String selfName}) =>
      RustLib.instance.api.crateApiMinosMobileClientNew(selfName: selfName);

  /// Construct a client preloaded with a durable pairing snapshot from the
  /// Dart-side secure store.
  static MobileClient newWithPersistedState({
    required String selfName,
    required PersistedPairingState state,
  }) => RustLib.instance.api.crateApiMinosMobileClientNewWithPersistedState(
    selfName: selfName,
    state: state,
  );

  /// Mark the app as backgrounded. Pauses the reconnect loop so we
  /// don't poke the backend while the OS is freezing the process.
  void notifyBackgrounded();

  /// Mark the app as foregrounded. Resets the reconnect backoff so the
  /// next connect attempt happens promptly.
  void notifyForegrounded();

  /// Pair using the raw JSON payload extracted from the scanned QR v2
  /// code. Delegates to `MobileClient::pair_with_qr_json`.
  Future<void> pairWithQrJson({required String qrJson});

  /// Export the current pairing snapshot so Dart can mirror it into secure
  /// storage after pairing succeeds.
  Future<PersistedPairingState> persistedPairingState();

  /// Read a window of translated UI events for one thread.
  Future<ReadThreadResponse> readThread({required ReadThreadParams req});

  /// Rotate the bearer + refresh tokens. Surfaces `Refreshing` /
  /// `Authenticated` / `RefreshFailed` transitions on the auth-state
  /// stream.
  Future<void> refreshSession();

  /// Register a new account on the backend. On success the bearer +
  /// refresh tokens are held in memory and surfaced via the auth-state
  /// stream; the reconnect loop then drives the WS back to `Connected`.
  Future<AuthSummary> register({
    required String email,
    required String password,
  });

  /// Reconnect using the durable pairing snapshot already loaded from the
  /// Dart-side secure store.
  Future<void> resumePersistedSession();

  /// Send a follow-up user message to an existing agent session.
  Future<void> sendUserMessage({
    required String sessionId,
    required String text,
  });

  /// Override the active Mac the next forward-RPC routes to.
  Future<void> setActiveHost({required String hostDeviceId});

  /// Start a new agent session and return the daemon-issued `session_id`
  /// (a.k.a. `thread_id`) plus the resolved workspace path. The caller is
  /// responsible for sending the first user message separately.
  Future<StartAgentResponse> startAgent({
    required AgentName agent,
    required String prompt,
  });

  /// Subscribe to auth-state transitions. Emits the current cached frame
  /// immediately, then every subsequent change. The spawned task exits
  /// once Dart drops the stream (detected via `sink.add(...).is_err()`).
  Stream<AuthStateFrame> subscribeAuthState();

  /// Subscribe to connection-state transitions. Emits the current value
  /// immediately, then every subsequent change. The spawned task exits once
  /// the Dart side drops the stream (detected via `sink.add(...).is_err()`).
  Stream<ConnectionState> subscribeState();

  /// Subscribe to live `UiEventFrame`s fanned out from the backend.
  /// Every frb stream sink gets its own broadcast receiver; lagging
  /// subscribers lose old frames rather than blocking the producer.
  Stream<UiEventFrame> subscribeUiEvents();
}

class AgentDescriptor {
  final AgentName name;
  final String? path;
  final String? version;
  final AgentStatus status;

  const AgentDescriptor({
    required this.name,
    this.path,
    this.version,
    required this.status,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ version.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentDescriptor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          version == other.version &&
          status == other.status;
}

enum AgentName { codex, claude, gemini }

@freezed
sealed class AgentStatus with _$AgentStatus {
  const AgentStatus._();

  const factory AgentStatus.ok() = AgentStatus_Ok;
  const factory AgentStatus.missing() = AgentStatus_Missing;
  const factory AgentStatus.error({required String reason}) = AgentStatus_Error;
}

@freezed
sealed class AuthStateFrame with _$AuthStateFrame {
  const AuthStateFrame._();

  const factory AuthStateFrame.unauthenticated() =
      AuthStateFrame_Unauthenticated;
  const factory AuthStateFrame.authenticated({required AuthSummary account}) =
      AuthStateFrame_Authenticated;
  const factory AuthStateFrame.refreshing() = AuthStateFrame_Refreshing;
  const factory AuthStateFrame.refreshFailed({required MinosError error}) =
      AuthStateFrame_RefreshFailed;
}

class AuthSummary {
  final String accountId;
  final String email;

  const AuthSummary({required this.accountId, required this.email});

  @override
  int get hashCode => accountId.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthSummary &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email;
}

@freezed
sealed class ConnectionState with _$ConnectionState {
  const ConnectionState._();

  const factory ConnectionState.disconnected() = ConnectionState_Disconnected;
  const factory ConnectionState.pairing() = ConnectionState_Pairing;
  const factory ConnectionState.connected() = ConnectionState_Connected;
  const factory ConnectionState.reconnecting({required int attempt}) =
      ConnectionState_Reconnecting;
}

enum ErrorKind {
  bindFailed,
  connectFailed,
  disconnected,
  pairingTokenInvalid,
  pairingStateMismatch,
  deviceNotTrusted,
  storeIo,
  storeCorrupt,
  cliProbeTimeout,
  cliProbeFailed,
  rpcCallFailed,
  unauthorized,
  connectionStateMismatch,
  envelopeVersionUnsupported,
  peerOffline,
  backendInternal,
  cfAuthFailed,
  codexSpawnFailed,
  codexConnectFailed,
  codexProtocolError,
  agentAlreadyRunning,
  agentNotRunning,
  agentNotSupported,
  agentSessionIdMismatch,
  cfAccessMisconfigured,
  ingestSeqConflict,
  threadNotFound,
  translationNotImplemented,
  translationFailed,
  pairingQrVersionUnsupported,
  timeout,
  notConnected,
  requestDropped,
  authRefreshFailed,
  emailTaken,
  weakPassword,
  rateLimited,
  invalidCredentials,
  agentStartFailed,
  pairingTokenExpired,
}

/// Dart-visible mirror of `minos_protocol::HostSummary`. One row in
/// `/v1/me/hosts`.
class HostSummaryDto {
  final String hostDeviceId;
  final String hostDisplayName;
  final PlatformInt64 pairedAtMs;
  final String pairedViaDeviceId;

  const HostSummaryDto({
    required this.hostDeviceId,
    required this.hostDisplayName,
    required this.pairedAtMs,
    required this.pairedViaDeviceId,
  });

  @override
  int get hashCode =>
      hostDeviceId.hashCode ^
      hostDisplayName.hashCode ^
      pairedAtMs.hashCode ^
      pairedViaDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostSummaryDto &&
          runtimeType == other.runtimeType &&
          hostDeviceId == other.hostDeviceId &&
          hostDisplayName == other.hostDisplayName &&
          pairedAtMs == other.pairedAtMs &&
          pairedViaDeviceId == other.pairedViaDeviceId;
}

enum Lang { zh, en }

class ListThreadsParams {
  final int limit;
  final PlatformInt64? beforeTsMs;
  final AgentName? agent;

  const ListThreadsParams({required this.limit, this.beforeTsMs, this.agent});

  @override
  int get hashCode => limit.hashCode ^ beforeTsMs.hashCode ^ agent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListThreadsParams &&
          runtimeType == other.runtimeType &&
          limit == other.limit &&
          beforeTsMs == other.beforeTsMs &&
          agent == other.agent;
}

class ListThreadsResponse {
  final List<ThreadSummary> threads;
  final PlatformInt64? nextBeforeTsMs;

  const ListThreadsResponse({required this.threads, this.nextBeforeTsMs});

  @override
  int get hashCode => threads.hashCode ^ nextBeforeTsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListThreadsResponse &&
          runtimeType == other.runtimeType &&
          threads == other.threads &&
          nextBeforeTsMs == other.nextBeforeTsMs;
}

/// Severity tag mirrored from `minos_mobile::log_capture::LogLevel`.
enum LogLevel { trace, debug, info, warn, error }

/// Single tracing event captured by the in-process ring buffer.
class LogRecord {
  final LogLevel level;
  final String target;
  final String message;
  final PlatformInt64 tsMs;

  const LogRecord({
    required this.level,
    required this.target,
    required this.message,
    required this.tsMs,
  });

  @override
  int get hashCode =>
      level.hashCode ^ target.hashCode ^ message.hashCode ^ tsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogRecord &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          target == other.target &&
          message == other.message &&
          tsMs == other.tsMs;
}

enum MessageRole { user, assistant, system }

@freezed
sealed class MinosError with _$MinosError implements FrbException {
  const MinosError._();

  const factory MinosError.bindFailed({
    required String addr,
    required String message,
  }) = MinosError_BindFailed;
  const factory MinosError.connectFailed({
    required String url,
    required String message,
  }) = MinosError_ConnectFailed;
  const factory MinosError.disconnected({required String reason}) =
      MinosError_Disconnected;
  const factory MinosError.pairingTokenInvalid() =
      MinosError_PairingTokenInvalid;
  const factory MinosError.pairingStateMismatch({
    required PairingState actual,
  }) = MinosError_PairingStateMismatch;
  const factory MinosError.deviceNotTrusted({required String deviceId}) =
      MinosError_DeviceNotTrusted;
  const factory MinosError.storeIo({
    required String path,
    required String message,
  }) = MinosError_StoreIo;
  const factory MinosError.storeCorrupt({
    required String path,
    required String message,
  }) = MinosError_StoreCorrupt;
  const factory MinosError.cliProbeTimeout({
    required String bin,
    required BigInt timeoutMs,
  }) = MinosError_CliProbeTimeout;
  const factory MinosError.cliProbeFailed({
    required String bin,
    required String message,
  }) = MinosError_CliProbeFailed;
  const factory MinosError.rpcCallFailed({
    required String method,
    required String message,
  }) = MinosError_RpcCallFailed;
  const factory MinosError.unauthorized({required String reason}) =
      MinosError_Unauthorized;
  const factory MinosError.connectionStateMismatch({
    required String expected,
    required String actual,
  }) = MinosError_ConnectionStateMismatch;
  const factory MinosError.envelopeVersionUnsupported({required int version}) =
      MinosError_EnvelopeVersionUnsupported;
  const factory MinosError.peerOffline({required String peerDeviceId}) =
      MinosError_PeerOffline;
  const factory MinosError.backendInternal({required String message}) =
      MinosError_BackendInternal;
  const factory MinosError.cfAuthFailed({required String message}) =
      MinosError_CfAuthFailed;
  const factory MinosError.codexSpawnFailed({required String message}) =
      MinosError_CodexSpawnFailed;
  const factory MinosError.codexConnectFailed({
    required String url,
    required String message,
  }) = MinosError_CodexConnectFailed;
  const factory MinosError.codexProtocolError({
    required String method,
    required String message,
  }) = MinosError_CodexProtocolError;
  const factory MinosError.agentAlreadyRunning() =
      MinosError_AgentAlreadyRunning;
  const factory MinosError.agentNotRunning() = MinosError_AgentNotRunning;
  const factory MinosError.agentNotSupported({required AgentName agent}) =
      MinosError_AgentNotSupported;
  const factory MinosError.agentSessionIdMismatch() =
      MinosError_AgentSessionIdMismatch;
  const factory MinosError.cfAccessMisconfigured({required String reason}) =
      MinosError_CfAccessMisconfigured;
  const factory MinosError.ingestSeqConflict({
    required String threadId,
    required BigInt seq,
  }) = MinosError_IngestSeqConflict;
  const factory MinosError.threadNotFound({required String threadId}) =
      MinosError_ThreadNotFound;
  const factory MinosError.translationNotImplemented({
    required AgentName agent,
  }) = MinosError_TranslationNotImplemented;
  const factory MinosError.translationFailed({
    required AgentName agent,
    required String message,
  }) = MinosError_TranslationFailed;
  const factory MinosError.pairingQrVersionUnsupported({required int version}) =
      MinosError_PairingQrVersionUnsupported;
  const factory MinosError.timeout() = MinosError_Timeout;
  const factory MinosError.notConnected() = MinosError_NotConnected;
  const factory MinosError.requestDropped() = MinosError_RequestDropped;
  const factory MinosError.authRefreshFailed({required String message}) =
      MinosError_AuthRefreshFailed;
  const factory MinosError.emailTaken() = MinosError_EmailTaken;
  const factory MinosError.weakPassword() = MinosError_WeakPassword;
  const factory MinosError.rateLimited({required int retryAfterS}) =
      MinosError_RateLimited;
  const factory MinosError.invalidCredentials() = MinosError_InvalidCredentials;
  const factory MinosError.agentStartFailed({required String reason}) =
      MinosError_AgentStartFailed;
  const factory MinosError.pairingTokenExpired() =
      MinosError_PairingTokenExpired;
}

enum PairingState { unpaired, awaitingPeer, paired }

/// Durable mobile pairing snapshot mirrored into the iOS keychain.
///
/// Phase 4 added the five auth fields (access/refresh tokens + bound
/// account identity) so the Dart-side secure store can rehydrate the full
/// session on cold launch. All five auth fields are persisted as a tuple —
/// either every one is present or all are `None`.
///
/// ADR-0020 dropped the device_secret from this snapshot — the iOS rail
/// is bearer-only.
///
/// Backend URL and CF Access service-token headers were dropped from the
/// snapshot when pairing transitioned to compile-time `build_config` — the
/// transport-edge values never round-trip through durable storage now.
class PersistedPairingState {
  final String? deviceId;
  final String? accessToken;
  final PlatformInt64? accessExpiresAtMs;
  final String? refreshToken;
  final String? accountId;
  final String? accountEmail;

  const PersistedPairingState({
    this.deviceId,
    this.accessToken,
    this.accessExpiresAtMs,
    this.refreshToken,
    this.accountId,
    this.accountEmail,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      accessToken.hashCode ^
      accessExpiresAtMs.hashCode ^
      refreshToken.hashCode ^
      accountId.hashCode ^
      accountEmail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersistedPairingState &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          accessExpiresAtMs == other.accessExpiresAtMs &&
          refreshToken == other.refreshToken &&
          accountId == other.accountId &&
          accountEmail == other.accountEmail;
}

class ReadThreadParams {
  final String threadId;
  final BigInt? fromSeq;
  final int limit;

  const ReadThreadParams({
    required this.threadId,
    this.fromSeq,
    required this.limit,
  });

  @override
  int get hashCode => threadId.hashCode ^ fromSeq.hashCode ^ limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadThreadParams &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          fromSeq == other.fromSeq &&
          limit == other.limit;
}

class ReadThreadResponse {
  final List<UiEventMessage> uiEvents;
  final BigInt? nextSeq;
  final ThreadEndReason? threadEndReason;

  const ReadThreadResponse({
    required this.uiEvents,
    this.nextSeq,
    this.threadEndReason,
  });

  @override
  int get hashCode =>
      uiEvents.hashCode ^ nextSeq.hashCode ^ threadEndReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadThreadResponse &&
          runtimeType == other.runtimeType &&
          uiEvents == other.uiEvents &&
          nextSeq == other.nextSeq &&
          threadEndReason == other.threadEndReason;
}

class RequestTraceRecord {
  final BigInt id;
  final RequestTraceTransport transport;
  final String method;
  final String target;
  final String? threadId;
  final String? requestSummary;
  final String? responseSummary;
  final String? errorDetail;
  final RequestTraceStatus status;
  final int? statusCode;
  final PlatformInt64 startedAtMs;
  final PlatformInt64? completedAtMs;
  final int? durationMs;

  const RequestTraceRecord({
    required this.id,
    required this.transport,
    required this.method,
    required this.target,
    this.threadId,
    this.requestSummary,
    this.responseSummary,
    this.errorDetail,
    required this.status,
    this.statusCode,
    required this.startedAtMs,
    this.completedAtMs,
    this.durationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      transport.hashCode ^
      method.hashCode ^
      target.hashCode ^
      threadId.hashCode ^
      requestSummary.hashCode ^
      responseSummary.hashCode ^
      errorDetail.hashCode ^
      status.hashCode ^
      statusCode.hashCode ^
      startedAtMs.hashCode ^
      completedAtMs.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestTraceRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          transport == other.transport &&
          method == other.method &&
          target == other.target &&
          threadId == other.threadId &&
          requestSummary == other.requestSummary &&
          responseSummary == other.responseSummary &&
          errorDetail == other.errorDetail &&
          status == other.status &&
          statusCode == other.statusCode &&
          startedAtMs == other.startedAtMs &&
          completedAtMs == other.completedAtMs &&
          durationMs == other.durationMs;
}

enum RequestTraceStatus { pending, success, failure }

enum RequestTraceTransport { http, rpc }

class StartAgentResponse {
  final String sessionId;
  final String cwd;

  const StartAgentResponse({required this.sessionId, required this.cwd});

  @override
  int get hashCode => sessionId.hashCode ^ cwd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartAgentResponse &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          cwd == other.cwd;
}

@freezed
sealed class ThreadEndReason with _$ThreadEndReason {
  const ThreadEndReason._();

  const factory ThreadEndReason.userStopped() = ThreadEndReason_UserStopped;
  const factory ThreadEndReason.agentDone() = ThreadEndReason_AgentDone;
  const factory ThreadEndReason.crashed({required String message}) =
      ThreadEndReason_Crashed;
  const factory ThreadEndReason.timeout() = ThreadEndReason_Timeout;
  const factory ThreadEndReason.hostDisconnected() =
      ThreadEndReason_HostDisconnected;
}

class ThreadSummary {
  final String threadId;
  final AgentName agent;
  final String? title;
  final PlatformInt64 firstTsMs;
  final PlatformInt64 lastTsMs;
  final int messageCount;
  final PlatformInt64? endedAtMs;
  final ThreadEndReason? endReason;

  const ThreadSummary({
    required this.threadId,
    required this.agent,
    this.title,
    required this.firstTsMs,
    required this.lastTsMs,
    required this.messageCount,
    this.endedAtMs,
    this.endReason,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^
      agent.hashCode ^
      title.hashCode ^
      firstTsMs.hashCode ^
      lastTsMs.hashCode ^
      messageCount.hashCode ^
      endedAtMs.hashCode ^
      endReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadSummary &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          agent == other.agent &&
          title == other.title &&
          firstTsMs == other.firstTsMs &&
          lastTsMs == other.lastTsMs &&
          messageCount == other.messageCount &&
          endedAtMs == other.endedAtMs &&
          endReason == other.endReason;
}

/// Dart-visible shape of `minos_mobile::UiEventFrame`. Held as a separate
/// type (rather than mirrored) so the `ui` field lands as the mirrored
/// `UiEventMessage` variant on the Dart side.
class UiEventFrame {
  final String threadId;
  final BigInt seq;
  final UiEventMessage ui;
  final PlatformInt64 tsMs;

  const UiEventFrame({
    required this.threadId,
    required this.seq,
    required this.ui,
    required this.tsMs,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^ seq.hashCode ^ ui.hashCode ^ tsMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEventFrame &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          seq == other.seq &&
          ui == other.ui &&
          tsMs == other.tsMs;
}

@freezed
sealed class UiEventMessage with _$UiEventMessage {
  const UiEventMessage._();

  const factory UiEventMessage.threadOpened({
    required String threadId,
    required AgentName agent,
    String? title,
    required PlatformInt64 openedAtMs,
  }) = UiEventMessage_ThreadOpened;
  const factory UiEventMessage.threadTitleUpdated({
    required String threadId,
    required String title,
  }) = UiEventMessage_ThreadTitleUpdated;
  const factory UiEventMessage.threadClosed({
    required String threadId,
    required ThreadEndReason reason,
    required PlatformInt64 closedAtMs,
  }) = UiEventMessage_ThreadClosed;
  const factory UiEventMessage.messageStarted({
    required String messageId,
    required MessageRole role,
    required PlatformInt64 startedAtMs,
  }) = UiEventMessage_MessageStarted;
  const factory UiEventMessage.messageCompleted({
    required String messageId,
    required PlatformInt64 finishedAtMs,
  }) = UiEventMessage_MessageCompleted;
  const factory UiEventMessage.textDelta({
    required String messageId,
    required String text,
  }) = UiEventMessage_TextDelta;
  const factory UiEventMessage.reasoningDelta({
    required String messageId,
    required String text,
  }) = UiEventMessage_ReasoningDelta;
  const factory UiEventMessage.toolCallPlaced({
    required String messageId,
    required String toolCallId,
    required String name,
    required String argsJson,
  }) = UiEventMessage_ToolCallPlaced;
  const factory UiEventMessage.toolCallCompleted({
    required String toolCallId,
    required String output,
    required bool isError,
  }) = UiEventMessage_ToolCallCompleted;
  const factory UiEventMessage.error({
    required String code,
    required String message,
    String? messageId,
  }) = UiEventMessage_Error;
  const factory UiEventMessage.raw({
    required String kind,
    required String payloadJson,
  }) = UiEventMessage_Raw;
}
