// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'minos.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `frb_runtime`, `spawn_state_forwarder`

/// Initialize mobile-side Rust logging with the given directory (supplied by
/// Dart, typically `<Documents>/Minos/Logs`). Idempotent — safe to call once
/// per launch.
Future<void> initLogging({required String logDir}) =>
    RustLib.instance.api.crateApiMinosInitLogging(logDir: logDir);

/// Localize an `ErrorKind` into user-facing copy. Mirrors the UniFFI adapter's
/// `kind_message` so Dart can render localized error strings without hard-
/// coding them.
String kindMessage({required ErrorKind kind, required Lang lang}) =>
    RustLib.instance.api.crateApiMinosKindMessage(kind: kind, lang: lang);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileClient>>
abstract class MobileClient implements RustOpaqueInterface {
  /// Current connection state, read from the watch-channel cache. Cheap and
  /// synchronous.
  ConnectionState currentState();

  /// Construct a client backed by the built-in in-memory pairing store.
  /// Synchronous — no I/O happens until a pairing method is called.
  factory MobileClient({required String selfName}) =>
      RustLib.instance.api.crateApiMinosMobileClientNew(selfName: selfName);

  /// Pair using the raw JSON payload extracted from the scanned QR code.
  /// Delegates to `MobileClient::pair_with_json`; see that method for the
  /// full error surface.
  Future<PairResponse> pairWithJson({required String qrJson});

  /// Subscribe to connection-state transitions. Emits the current value
  /// immediately, then every subsequent change. The spawned task exits once
  /// the Dart side drops the stream (detected via `sink.add(...).is_err()`).
  Stream<ConnectionState> subscribeState();
}

enum AgentName { codex, claude, gemini }

@freezed
sealed class ConnectionState with _$ConnectionState {
  const ConnectionState._();

  const factory ConnectionState.disconnected() = ConnectionState_Disconnected;
  const factory ConnectionState.pairing() = ConnectionState_Pairing;
  const factory ConnectionState.connected() = ConnectionState_Connected;
  const factory ConnectionState.reconnecting({required int attempt}) =
      ConnectionState_Reconnecting;
}

enum ErrorKind {
  bindFailed,
  connectFailed,
  disconnected,
  pairingTokenInvalid,
  pairingStateMismatch,
  deviceNotTrusted,
  storeIo,
  storeCorrupt,
  cliProbeTimeout,
  cliProbeFailed,
  rpcCallFailed,
  unauthorized,
  connectionStateMismatch,
  envelopeVersionUnsupported,
  peerOffline,
  relayInternal,
  codexSpawnFailed,
  codexConnectFailed,
  codexProtocolError,
  agentAlreadyRunning,
  agentNotRunning,
  agentNotSupported,
  agentSessionIdMismatch,
}

enum Lang { zh, en }

@freezed
sealed class MinosError with _$MinosError implements FrbException {
  const MinosError._();

  const factory MinosError.bindFailed({
    required String addr,
    required String message,
  }) = MinosError_BindFailed;
  const factory MinosError.connectFailed({
    required String url,
    required String message,
  }) = MinosError_ConnectFailed;
  const factory MinosError.disconnected({required String reason}) =
      MinosError_Disconnected;
  const factory MinosError.pairingTokenInvalid() =
      MinosError_PairingTokenInvalid;
  const factory MinosError.pairingStateMismatch({
    required PairingState actual,
  }) = MinosError_PairingStateMismatch;
  const factory MinosError.deviceNotTrusted({required String deviceId}) =
      MinosError_DeviceNotTrusted;
  const factory MinosError.storeIo({
    required String path,
    required String message,
  }) = MinosError_StoreIo;
  const factory MinosError.storeCorrupt({
    required String path,
    required String message,
  }) = MinosError_StoreCorrupt;
  const factory MinosError.cliProbeTimeout({
    required String bin,
    required BigInt timeoutMs,
  }) = MinosError_CliProbeTimeout;
  const factory MinosError.cliProbeFailed({
    required String bin,
    required String message,
  }) = MinosError_CliProbeFailed;
  const factory MinosError.rpcCallFailed({
    required String method,
    required String message,
  }) = MinosError_RpcCallFailed;
  const factory MinosError.unauthorized({required String reason}) =
      MinosError_Unauthorized;
  const factory MinosError.connectionStateMismatch({
    required String expected,
    required String actual,
  }) = MinosError_ConnectionStateMismatch;
  const factory MinosError.envelopeVersionUnsupported({required int version}) =
      MinosError_EnvelopeVersionUnsupported;
  const factory MinosError.peerOffline({required String peerDeviceId}) =
      MinosError_PeerOffline;
  const factory MinosError.relayInternal({required String message}) =
      MinosError_RelayInternal;
  const factory MinosError.codexSpawnFailed({required String message}) =
      MinosError_CodexSpawnFailed;
  const factory MinosError.codexConnectFailed({
    required String url,
    required String message,
  }) = MinosError_CodexConnectFailed;
  const factory MinosError.codexProtocolError({
    required String method,
    required String message,
  }) = MinosError_CodexProtocolError;
  const factory MinosError.agentAlreadyRunning() =
      MinosError_AgentAlreadyRunning;
  const factory MinosError.agentNotRunning() = MinosError_AgentNotRunning;
  const factory MinosError.agentNotSupported({required AgentName agent}) =
      MinosError_AgentNotSupported;
  const factory MinosError.agentSessionIdMismatch() =
      MinosError_AgentSessionIdMismatch;
}

class PairResponse {
  final bool ok;
  final String macName;

  const PairResponse({required this.ok, required this.macName});

  @override
  int get hashCode => ok.hashCode ^ macName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairResponse &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          macName == other.macName;
}

enum PairingState { unpaired, awaitingPeer, paired }
